/**
 * Map data of Earth to add to the graph.
 * 
 * February 23rd, 2024
 * 
 * Alex McColm
 *
 **/
#ifndef WORLD_H
#define WORLD_H
char * AF_name;
char * AL_name;
char * DZ_name;
char * AD_name;
char * AO_name;
char * AR_name;
char * AM_name;
char * AT_name;
char * AZ_name;
char * BD_name;
char * BY_name;
char * BE_name;
char * BZ_name;
char * BJ_name;
char * BT_name;
char * BO_name;
char * BA_name;
char * BW_name;
char * BR_name;
char * BN_name;
char * BG_name;
char * BF_name;
char * BI_name;
char * KH_name;
char * CM_name;
char * CA_name;
char * CF_name;
char * TD_name;
char * CL_name;
char * CN_name;
char * CO_name;
char * CG_name;
char * CD_name;
char * CR_name;
char * CI_name;
char * HR_name;
char * CZ_name;
char * DK_name;
char * DJ_name;
char * DO_name;
char * EC_name;
char * EG_name;
char * SV_name;
char * GQ_name;
char * ER_name;
char * EE_name;
char * SZ_name;
char * ET_name;
char * FI_name;
char * FR_name;
char * GF_name;
char * GA_name;
char * GM_name;
char * GE_name;
char * DE_name;
char * GH_name;
char * GI_name;
char * GR_name;
char * GT_name;
char * GN_name;
char * GW_name;
char * GY_name;
char * HT_name;
char * VA_name;
char * HN_name;
char * HK_name;
char * HU_name;
char * IN_name;
char * ID_name;
char * IR_name;
char * IQ_name;
char * IE_name;
char * IL_name;
char * IT_name;
char * JO_name;
char * KZ_name;
char * KE_name;
char * KP_name;
char * KR_name;
char * KW_name;
char * KG_name;
char * LA_name;
char * LV_name;
char * LB_name;
char * LS_name;
char * LR_name;
char * LY_name;
char * LI_name;
char * LT_name;
char * LU_name;
char * MO_name;
char * MW_name;
char * MY_name;
char * ML_name;
char * MR_name;
char * MX_name;
char * MD_name;
char * MC_name;
char * MN_name;
char * ME_name;
char * MA_name;
char * MZ_name;
char * MM_name;
char * NA_name;
char * NP_name;
char * NL_name;
char * NI_name;
char * NE_name;
char * NG_name;
char * MK_name;
char * NO_name;
char * OM_name;
char * PK_name;
char * PS_name;
char * PA_name;
char * PG_name;
char * PY_name;
char * PE_name;
char * PL_name;
char * PT_name;
char * QA_name;
char * RO_name;
char * RU_name;
char * RW_name;
char * MF_name;
char * SM_name;
char * SA_name;
char * SN_name;
char * RS_name;
char * SL_name;
char * SX_name;
char * SK_name;
char * SI_name;
char * SO_name;
char * ZA_name;
char * SS_name;
char * ES_name;
char * SD_name;
char * SR_name;
char * SE_name;
char * CH_name;
char * SY_name;
char * TW_name;
char * TJ_name;
char * TZ_name;
char * TH_name;
char * TL_name;
char * TG_name;
char * TN_name;
char * TR_name;
char * TM_name;
char * UG_name;
char * UA_name;
char * AE_name;
char * GB_name;
char * US_name;
char * UM_name;
char * UY_name;
char * UZ_name;
char * VE_name;
char * VN_name;
char * EH_name;
char * YE_name;
char * ZM_name;
char * ZW_name;
char * AF_alpha2;
char * AL_alpha2;
char * DZ_alpha2;
char * AD_alpha2;
char * AO_alpha2;
char * AR_alpha2;
char * AM_alpha2;
char * AT_alpha2;
char * AZ_alpha2;
char * BD_alpha2;
char * BY_alpha2;
char * BE_alpha2;
char * BZ_alpha2;
char * BJ_alpha2;
char * BT_alpha2;
char * BO_alpha2;
char * BA_alpha2;
char * BW_alpha2;
char * BR_alpha2;
char * BN_alpha2;
char * BG_alpha2;
char * BF_alpha2;
char * BI_alpha2;
char * KH_alpha2;
char * CM_alpha2;
char * CA_alpha2;
char * CF_alpha2;
char * TD_alpha2;
char * CL_alpha2;
char * CN_alpha2;
char * CO_alpha2;
char * CG_alpha2;
char * CD_alpha2;
char * CR_alpha2;
char * CI_alpha2;
char * HR_alpha2;
char * CZ_alpha2;
char * DK_alpha2;
char * DJ_alpha2;
char * DO_alpha2;
char * EC_alpha2;
char * EG_alpha2;
char * SV_alpha2;
char * GQ_alpha2;
char * ER_alpha2;
char * EE_alpha2;
char * SZ_alpha2;
char * ET_alpha2;
char * FI_alpha2;
char * FR_alpha2;
char * GF_alpha2;
char * GA_alpha2;
char * GM_alpha2;
char * GE_alpha2;
char * DE_alpha2;
char * GH_alpha2;
char * GI_alpha2;
char * GR_alpha2;
char * GT_alpha2;
char * GN_alpha2;
char * GW_alpha2;
char * GY_alpha2;
char * HT_alpha2;
char * VA_alpha2;
char * HN_alpha2;
char * HK_alpha2;
char * HU_alpha2;
char * IN_alpha2;
char * ID_alpha2;
char * IR_alpha2;
char * IQ_alpha2;
char * IE_alpha2;
char * IL_alpha2;
char * IT_alpha2;
char * JO_alpha2;
char * KZ_alpha2;
char * KE_alpha2;
char * KP_alpha2;
char * KR_alpha2;
char * KW_alpha2;
char * KG_alpha2;
char * LA_alpha2;
char * LV_alpha2;
char * LB_alpha2;
char * LS_alpha2;
char * LR_alpha2;
char * LY_alpha2;
char * LI_alpha2;
char * LT_alpha2;
char * LU_alpha2;
char * MO_alpha2;
char * MW_alpha2;
char * MY_alpha2;
char * ML_alpha2;
char * MR_alpha2;
char * MX_alpha2;
char * MD_alpha2;
char * MC_alpha2;
char * MN_alpha2;
char * ME_alpha2;
char * MA_alpha2;
char * MZ_alpha2;
char * MM_alpha2;
char * NA_alpha2;
char * NP_alpha2;
char * NL_alpha2;
char * NI_alpha2;
char * NE_alpha2;
char * NG_alpha2;
char * MK_alpha2;
char * NO_alpha2;
char * OM_alpha2;
char * PK_alpha2;
char * PS_alpha2;
char * PA_alpha2;
char * PG_alpha2;
char * PY_alpha2;
char * PE_alpha2;
char * PL_alpha2;
char * PT_alpha2;
char * QA_alpha2;
char * RO_alpha2;
char * RU_alpha2;
char * RW_alpha2;
char * MF_alpha2;
char * SM_alpha2;
char * SA_alpha2;
char * SN_alpha2;
char * RS_alpha2;
char * SL_alpha2;
char * SX_alpha2;
char * SK_alpha2;
char * SI_alpha2;
char * SO_alpha2;
char * ZA_alpha2;
char * SS_alpha2;
char * ES_alpha2;
char * SD_alpha2;
char * SR_alpha2;
char * SE_alpha2;
char * CH_alpha2;
char * SY_alpha2;
char * TW_alpha2;
char * TJ_alpha2;
char * TZ_alpha2;
char * TH_alpha2;
char * TL_alpha2;
char * TG_alpha2;
char * TN_alpha2;
char * TR_alpha2;
char * TM_alpha2;
char * UG_alpha2;
char * UA_alpha2;
char * AE_alpha2;
char * GB_alpha2;
char * US_alpha2;
char * UM_alpha2;
char * UY_alpha2;
char * UZ_alpha2;
char * VE_alpha2;
char * VN_alpha2;
char * EH_alpha2;
char * YE_alpha2;
char * ZM_alpha2;
char * ZW_alpha2;

extern char * AF_name;
extern char * AL_name;
extern char * DZ_name;
extern char * AD_name;
extern char * AO_name;
extern char * AR_name;
extern char * AM_name;
extern char * AT_name;
extern char * AZ_name;
extern char * BD_name;
extern char * BY_name;
extern char * BE_name;
extern char * BZ_name;
extern char * BJ_name;
extern char * BT_name;
extern char * BO_name;
extern char * BA_name;
extern char * BW_name;
extern char * BR_name;
extern char * BN_name;
extern char * BG_name;
extern char * BF_name;
extern char * BI_name;
extern char * KH_name;
extern char * CM_name;
extern char * CA_name;
extern char * CF_name;
extern char * TD_name;
extern char * CL_name;
extern char * CN_name;
extern char * CO_name;
extern char * CG_name;
extern char * CD_name;
extern char * CR_name;
extern char * CI_name;
extern char * HR_name;
extern char * CZ_name;
extern char * DK_name;
extern char * DJ_name;
extern char * DO_name;
extern char * EC_name;
extern char * EG_name;
extern char * SV_name;
extern char * GQ_name;
extern char * ER_name;
extern char * EE_name;
extern char * SZ_name;
extern char * ET_name;
extern char * FI_name;
extern char * FR_name;
extern char * GF_name;
extern char * GA_name;
extern char * GM_name;
extern char * GE_name;
extern char * DE_name;
extern char * GH_name;
extern char * GI_name;
extern char * GR_name;
extern char * GT_name;
extern char * GN_name;
extern char * GW_name;
extern char * GY_name;
extern char * HT_name;
extern char * VA_name;
extern char * HN_name;
extern char * HK_name;
extern char * HU_name;
extern char * IN_name;
extern char * ID_name;
extern char * IR_name;
extern char * IQ_name;
extern char * IE_name;
extern char * IL_name;
extern char * IT_name;
extern char * JO_name;
extern char * KZ_name;
extern char * KE_name;
extern char * KP_name;
extern char * KR_name;
extern char * KW_name;
extern char * KG_name;
extern char * LA_name;
extern char * LV_name;
extern char * LB_name;
extern char * LS_name;
extern char * LR_name;
extern char * LY_name;
extern char * LI_name;
extern char * LT_name;
extern char * LU_name;
extern char * MO_name;
extern char * MW_name;
extern char * MY_name;
extern char * ML_name;
extern char * MR_name;
extern char * MX_name;
extern char * MD_name;
extern char * MC_name;
extern char * MN_name;
extern char * ME_name;
extern char * MA_name;
extern char * MZ_name;
extern char * MM_name;
extern char * NA_name;
extern char * NP_name;
extern char * NL_name;
extern char * NI_name;
extern char * NE_name;
extern char * NG_name;
extern char * MK_name;
extern char * NO_name;
extern char * OM_name;
extern char * PK_name;
extern char * PS_name;
extern char * PA_name;
extern char * PG_name;
extern char * PY_name;
extern char * PE_name;
extern char * PL_name;
extern char * PT_name;
extern char * QA_name;
extern char * RO_name;
extern char * RU_name;
extern char * RW_name;
extern char * MF_name;
extern char * SM_name;
extern char * SA_name;
extern char * SN_name;
extern char * RS_name;
extern char * SL_name;
extern char * SX_name;
extern char * SK_name;
extern char * SI_name;
extern char * SO_name;
extern char * ZA_name;
extern char * SS_name;
extern char * ES_name;
extern char * SD_name;
extern char * SR_name;
extern char * SE_name;
extern char * CH_name;
extern char * SY_name;
extern char * TW_name;
extern char * TJ_name;
extern char * TZ_name;
extern char * TH_name;
extern char * TL_name;
extern char * TG_name;
extern char * TN_name;
extern char * TR_name;
extern char * TM_name;
extern char * UG_name;
extern char * UA_name;
extern char * AE_name;
extern char * GB_name;
extern char * US_name;
extern char * UM_name;
extern char * UY_name;
extern char * UZ_name;
extern char * VE_name;
extern char * VN_name;
extern char * EH_name;
extern char * YE_name;
extern char * ZM_name;
extern char * ZW_name;
extern char * AF_alpha2;
extern char * AL_alpha2;
extern char * DZ_alpha2;
extern char * AD_alpha2;
extern char * AO_alpha2;
extern char * AR_alpha2;
extern char * AM_alpha2;
extern char * AT_alpha2;
extern char * AZ_alpha2;
extern char * BD_alpha2;
extern char * BY_alpha2;
extern char * BE_alpha2;
extern char * BZ_alpha2;
extern char * BJ_alpha2;
extern char * BT_alpha2;
extern char * BO_alpha2;
extern char * BA_alpha2;
extern char * BW_alpha2;
extern char * BR_alpha2;
extern char * BN_alpha2;
extern char * BG_alpha2;
extern char * BF_alpha2;
extern char * BI_alpha2;
extern char * KH_alpha2;
extern char * CM_alpha2;
extern char * CA_alpha2;
extern char * CF_alpha2;
extern char * TD_alpha2;
extern char * CL_alpha2;
extern char * CN_alpha2;
extern char * CO_alpha2;
extern char * CG_alpha2;
extern char * CD_alpha2;
extern char * CR_alpha2;
extern char * CI_alpha2;
extern char * HR_alpha2;
extern char * CZ_alpha2;
extern char * DK_alpha2;
extern char * DJ_alpha2;
extern char * DO_alpha2;
extern char * EC_alpha2;
extern char * EG_alpha2;
extern char * SV_alpha2;
extern char * GQ_alpha2;
extern char * ER_alpha2;
extern char * EE_alpha2;
extern char * SZ_alpha2;
extern char * ET_alpha2;
extern char * FI_alpha2;
extern char * FR_alpha2;
extern char * GF_alpha2;
extern char * GA_alpha2;
extern char * GM_alpha2;
extern char * GE_alpha2;
extern char * DE_alpha2;
extern char * GH_alpha2;
extern char * GI_alpha2;
extern char * GR_alpha2;
extern char * GT_alpha2;
extern char * GN_alpha2;
extern char * GW_alpha2;
extern char * GY_alpha2;
extern char * HT_alpha2;
extern char * VA_alpha2;
extern char * HN_alpha2;
extern char * HK_alpha2;
extern char * HU_alpha2;
extern char * IN_alpha2;
extern char * ID_alpha2;
extern char * IR_alpha2;
extern char * IQ_alpha2;
extern char * IE_alpha2;
extern char * IL_alpha2;
extern char * IT_alpha2;
extern char * JO_alpha2;
extern char * KZ_alpha2;
extern char * KE_alpha2;
extern char * KP_alpha2;
extern char * KR_alpha2;
extern char * KW_alpha2;
extern char * KG_alpha2;
extern char * LA_alpha2;
extern char * LV_alpha2;
extern char * LB_alpha2;
extern char * LS_alpha2;
extern char * LR_alpha2;
extern char * LY_alpha2;
extern char * LI_alpha2;
extern char * LT_alpha2;
extern char * LU_alpha2;
extern char * MO_alpha2;
extern char * MW_alpha2;
extern char * MY_alpha2;
extern char * ML_alpha2;
extern char * MR_alpha2;
extern char * MX_alpha2;
extern char * MD_alpha2;
extern char * MC_alpha2;
extern char * MN_alpha2;
extern char * ME_alpha2;
extern char * MA_alpha2;
extern char * MZ_alpha2;
extern char * MM_alpha2;
extern char * NA_alpha2;
extern char * NP_alpha2;
extern char * NL_alpha2;
extern char * NI_alpha2;
extern char * NE_alpha2;
extern char * NG_alpha2;
extern char * MK_alpha2;
extern char * NO_alpha2;
extern char * OM_alpha2;
extern char * PK_alpha2;
extern char * PS_alpha2;
extern char * PA_alpha2;
extern char * PG_alpha2;
extern char * PY_alpha2;
extern char * PE_alpha2;
extern char * PL_alpha2;
extern char * PT_alpha2;
extern char * QA_alpha2;
extern char * RO_alpha2;
extern char * RU_alpha2;
extern char * RW_alpha2;
extern char * MF_alpha2;
extern char * SM_alpha2;
extern char * SA_alpha2;
extern char * SN_alpha2;
extern char * RS_alpha2;
extern char * SL_alpha2;
extern char * SX_alpha2;
extern char * SK_alpha2;
extern char * SI_alpha2;
extern char * SO_alpha2;
extern char * ZA_alpha2;
extern char * SS_alpha2;
extern char * ES_alpha2;
extern char * SD_alpha2;
extern char * SR_alpha2;
extern char * SE_alpha2;
extern char * CH_alpha2;
extern char * SY_alpha2;
extern char * TW_alpha2;
extern char * TJ_alpha2;
extern char * TZ_alpha2;
extern char * TH_alpha2;
extern char * TL_alpha2;
extern char * TG_alpha2;
extern char * TN_alpha2;
extern char * TR_alpha2;
extern char * TM_alpha2;
extern char * UG_alpha2;
extern char * UA_alpha2;
extern char * AE_alpha2;
extern char * GB_alpha2;
extern char * US_alpha2;
extern char * UM_alpha2;
extern char * UY_alpha2;
extern char * UZ_alpha2;
extern char * VE_alpha2;
extern char * VN_alpha2;
extern char * EH_alpha2;
extern char * YE_alpha2;
extern char * ZM_alpha2;
extern char * ZW_alpha2;

extern struct Vertex * country_AF;
extern struct Vertex * country_AL;
extern struct Vertex * country_DZ;
extern struct Vertex * country_AD;
extern struct Vertex * country_AO;
extern struct Vertex * country_AR;
extern struct Vertex * country_AM;
extern struct Vertex * country_AT;
extern struct Vertex * country_AZ;
extern struct Vertex * country_BD;
extern struct Vertex * country_BY;
extern struct Vertex * country_BE;
extern struct Vertex * country_BZ;
extern struct Vertex * country_BJ;
extern struct Vertex * country_BT;
extern struct Vertex * country_BO;
extern struct Vertex * country_BA;
extern struct Vertex * country_BW;
extern struct Vertex * country_BR;
extern struct Vertex * country_BN;
extern struct Vertex * country_BG;
extern struct Vertex * country_BF;
extern struct Vertex * country_BI;
extern struct Vertex * country_KH;
extern struct Vertex * country_CM;
extern struct Vertex * country_CA;
extern struct Vertex * country_CF;
extern struct Vertex * country_TD;
extern struct Vertex * country_CL;
extern struct Vertex * country_CN;
extern struct Vertex * country_CO;
extern struct Vertex * country_CG;
extern struct Vertex * country_CD;
extern struct Vertex * country_CR;
extern struct Vertex * country_CI;
extern struct Vertex * country_HR;
extern struct Vertex * country_CZ;
extern struct Vertex * country_DK;
extern struct Vertex * country_DJ;
extern struct Vertex * country_DO;
extern struct Vertex * country_EC;
extern struct Vertex * country_EG;
extern struct Vertex * country_SV;
extern struct Vertex * country_GQ;
extern struct Vertex * country_ER;
extern struct Vertex * country_EE;
extern struct Vertex * country_SZ;
extern struct Vertex * country_ET;
extern struct Vertex * country_FI;
extern struct Vertex * country_FR;
extern struct Vertex * country_GF;
extern struct Vertex * country_GA;
extern struct Vertex * country_GM;
extern struct Vertex * country_GE;
extern struct Vertex * country_DE;
extern struct Vertex * country_GH;
extern struct Vertex * country_GI;
extern struct Vertex * country_GR;
extern struct Vertex * country_GT;
extern struct Vertex * country_GN;
extern struct Vertex * country_GW;
extern struct Vertex * country_GY;
extern struct Vertex * country_HT;
extern struct Vertex * country_VA;
extern struct Vertex * country_HN;
extern struct Vertex * country_HK;
extern struct Vertex * country_HU;
extern struct Vertex * country_IN;
extern struct Vertex * country_ID;
extern struct Vertex * country_IR;
extern struct Vertex * country_IQ;
extern struct Vertex * country_IE;
extern struct Vertex * country_IL;
extern struct Vertex * country_IT;
extern struct Vertex * country_JO;
extern struct Vertex * country_KZ;
extern struct Vertex * country_KE;
extern struct Vertex * country_KP;
extern struct Vertex * country_KR;
extern struct Vertex * country_KW;
extern struct Vertex * country_KG;
extern struct Vertex * country_LA;
extern struct Vertex * country_LV;
extern struct Vertex * country_LB;
extern struct Vertex * country_LS;
extern struct Vertex * country_LR;
extern struct Vertex * country_LY;
extern struct Vertex * country_LI;
extern struct Vertex * country_LT;
extern struct Vertex * country_LU;
extern struct Vertex * country_MO;
extern struct Vertex * country_MW;
extern struct Vertex * country_MY;
extern struct Vertex * country_ML;
extern struct Vertex * country_MR;
extern struct Vertex * country_MX;
extern struct Vertex * country_MD;
extern struct Vertex * country_MC;
extern struct Vertex * country_MN;
extern struct Vertex * country_ME;
extern struct Vertex * country_MA;
extern struct Vertex * country_MZ;
extern struct Vertex * country_MM;
extern struct Vertex * country_NA;
extern struct Vertex * country_NP;
extern struct Vertex * country_NL;
extern struct Vertex * country_NI;
extern struct Vertex * country_NE;
extern struct Vertex * country_NG;
extern struct Vertex * country_MK;
extern struct Vertex * country_NO;
extern struct Vertex * country_OM;
extern struct Vertex * country_PK;
extern struct Vertex * country_PS;
extern struct Vertex * country_PA;
extern struct Vertex * country_PG;
extern struct Vertex * country_PY;
extern struct Vertex * country_PE;
extern struct Vertex * country_PL;
extern struct Vertex * country_PT;
extern struct Vertex * country_QA;
extern struct Vertex * country_RO;
extern struct Vertex * country_RU;
extern struct Vertex * country_RW;
extern struct Vertex * country_MF;
extern struct Vertex * country_SM;
extern struct Vertex * country_SA;
extern struct Vertex * country_SN;
extern struct Vertex * country_RS;
extern struct Vertex * country_SL;
extern struct Vertex * country_SX;
extern struct Vertex * country_SK;
extern struct Vertex * country_SI;
extern struct Vertex * country_SO;
extern struct Vertex * country_ZA;
extern struct Vertex * country_SS;
extern struct Vertex * country_ES;
extern struct Vertex * country_SD;
extern struct Vertex * country_SR;
extern struct Vertex * country_SE;
extern struct Vertex * country_CH;
extern struct Vertex * country_SY;
extern struct Vertex * country_TW;
extern struct Vertex * country_TJ;
extern struct Vertex * country_TZ;
extern struct Vertex * country_TH;
extern struct Vertex * country_TL;
extern struct Vertex * country_TG;
extern struct Vertex * country_TN;
extern struct Vertex * country_TR;
extern struct Vertex * country_TM;
extern struct Vertex * country_UG;
extern struct Vertex * country_UA;
extern struct Vertex * country_AE;
extern struct Vertex * country_GB;
extern struct Vertex * country_US;
extern struct Vertex * country_UM;
extern struct Vertex * country_UY;
extern struct Vertex * country_UZ;
extern struct Vertex * country_VE;
extern struct Vertex * country_VN;
extern struct Vertex * country_EH;
extern struct Vertex * country_YE;
extern struct Vertex * country_ZM;
extern struct Vertex * country_ZW;

struct Vertex * country_AF;
struct Vertex * country_AL;
struct Vertex * country_DZ;
struct Vertex * country_AD;
struct Vertex * country_AO;
struct Vertex * country_AR;
struct Vertex * country_AM;
struct Vertex * country_AT;
struct Vertex * country_AZ;
struct Vertex * country_BD;
struct Vertex * country_BY;
struct Vertex * country_BE;
struct Vertex * country_BZ;
struct Vertex * country_BJ;
struct Vertex * country_BT;
struct Vertex * country_BO;
struct Vertex * country_BA;
struct Vertex * country_BW;
struct Vertex * country_BR;
struct Vertex * country_BN;
struct Vertex * country_BG;
struct Vertex * country_BF;
struct Vertex * country_BI;
struct Vertex * country_KH;
struct Vertex * country_CM;
struct Vertex * country_CA;
struct Vertex * country_CF;
struct Vertex * country_TD;
struct Vertex * country_CL;
struct Vertex * country_CN;
struct Vertex * country_CO;
struct Vertex * country_CG;
struct Vertex * country_CD;
struct Vertex * country_CR;
struct Vertex * country_CI;
struct Vertex * country_HR;
struct Vertex * country_CZ;
struct Vertex * country_DK;
struct Vertex * country_DJ;
struct Vertex * country_DO;
struct Vertex * country_EC;
struct Vertex * country_EG;
struct Vertex * country_SV;
struct Vertex * country_GQ;
struct Vertex * country_ER;
struct Vertex * country_EE;
struct Vertex * country_SZ;
struct Vertex * country_ET;
struct Vertex * country_FI;
struct Vertex * country_FR;
struct Vertex * country_GF;
struct Vertex * country_GA;
struct Vertex * country_GM;
struct Vertex * country_GE;
struct Vertex * country_DE;
struct Vertex * country_GH;
struct Vertex * country_GI;
struct Vertex * country_GR;
struct Vertex * country_GT;
struct Vertex * country_GN;
struct Vertex * country_GW;
struct Vertex * country_GY;
struct Vertex * country_HT;
struct Vertex * country_VA;
struct Vertex * country_HN;
struct Vertex * country_HK;
struct Vertex * country_HU;
struct Vertex * country_IN;
struct Vertex * country_ID;
struct Vertex * country_IR;
struct Vertex * country_IQ;
struct Vertex * country_IE;
struct Vertex * country_IL;
struct Vertex * country_IT;
struct Vertex * country_JO;
struct Vertex * country_KZ;
struct Vertex * country_KE;
struct Vertex * country_KP;
struct Vertex * country_KR;
struct Vertex * country_KW;
struct Vertex * country_KG;
struct Vertex * country_LA;
struct Vertex * country_LV;
struct Vertex * country_LB;
struct Vertex * country_LS;
struct Vertex * country_LR;
struct Vertex * country_LY;
struct Vertex * country_LI;
struct Vertex * country_LT;
struct Vertex * country_LU;
struct Vertex * country_MO;
struct Vertex * country_MW;
struct Vertex * country_MY;
struct Vertex * country_ML;
struct Vertex * country_MR;
struct Vertex * country_MX;
struct Vertex * country_MD;
struct Vertex * country_MC;
struct Vertex * country_MN;
struct Vertex * country_ME;
struct Vertex * country_MA;
struct Vertex * country_MZ;
struct Vertex * country_MM;
struct Vertex * country_NA;
struct Vertex * country_NP;
struct Vertex * country_NL;
struct Vertex * country_NI;
struct Vertex * country_NE;
struct Vertex * country_NG;
struct Vertex * country_MK;
struct Vertex * country_NO;
struct Vertex * country_OM;
struct Vertex * country_PK;
struct Vertex * country_PS;
struct Vertex * country_PA;
struct Vertex * country_PG;
struct Vertex * country_PY;
struct Vertex * country_PE;
struct Vertex * country_PL;
struct Vertex * country_PT;
struct Vertex * country_QA;
struct Vertex * country_RO;
struct Vertex * country_RU;
struct Vertex * country_RW;
struct Vertex * country_MF;
struct Vertex * country_SM;
struct Vertex * country_SA;
struct Vertex * country_SN;
struct Vertex * country_RS;
struct Vertex * country_SL;
struct Vertex * country_SX;
struct Vertex * country_SK;
struct Vertex * country_SI;
struct Vertex * country_SO;
struct Vertex * country_ZA;
struct Vertex * country_SS;
struct Vertex * country_ES;
struct Vertex * country_SD;
struct Vertex * country_SR;
struct Vertex * country_SE;
struct Vertex * country_CH;
struct Vertex * country_SY;
struct Vertex * country_TW;
struct Vertex * country_TJ;
struct Vertex * country_TZ;
struct Vertex * country_TH;
struct Vertex * country_TL;
struct Vertex * country_TG;
struct Vertex * country_TN;
struct Vertex * country_TR;
struct Vertex * country_TM;
struct Vertex * country_UG;
struct Vertex * country_UA;
struct Vertex * country_AE;
struct Vertex * country_GB;
struct Vertex * country_US;
struct Vertex * country_UM;
struct Vertex * country_UY;
struct Vertex * country_UZ;
struct Vertex * country_VE;
struct Vertex * country_VN;
struct Vertex * country_EH;
struct Vertex * country_YE;
struct Vertex * country_ZM;
struct Vertex * country_ZW;
#endif // WORLD_H