/*
 * January 2nd, 2024
 *
 * world.c
 *
 * Graph of all countries in the world that have one or more
 * land borders with another country.
 */
#include <string.h>
#include "../include/hash_table.h"
#include "../include/graph.h"

int main(void)
{
	// Set up ISO3 -> country name dictionary
	struct hash_table * alpha2_to_name = dictionary_create(500);

	// Populate ISO3 -> country names
	dictionary_insert(alpha2_to_name, strdup("AF"), strdup("Afghanistan"));
	dictionary_insert(alpha2_to_name, strdup("AX"), strdup("Åland Islands"));
	dictionary_insert(alpha2_to_name, strdup("AL"), strdup("Albania"));
	dictionary_insert(alpha2_to_name, strdup("DZ"), strdup("Algeria"));
	dictionary_insert(alpha2_to_name, strdup("AS"), strdup("American Samoa"));
	dictionary_insert(alpha2_to_name, strdup("AD"), strdup("Andorra"));
	dictionary_insert(alpha2_to_name, strdup("AO"), strdup("Angola"));
	dictionary_insert(alpha2_to_name, strdup("AI"), strdup("Anguilla"));
	dictionary_insert(alpha2_to_name, strdup("AQ"), strdup("Antarctica"));
	dictionary_insert(alpha2_to_name, strdup("AG"), strdup("Antigua and Barbuda"));
	dictionary_insert(alpha2_to_name, strdup("AR"), strdup("Argentina"));
	dictionary_insert(alpha2_to_name, strdup("AM"), strdup("Armenia"));
	dictionary_insert(alpha2_to_name, strdup("AW"), strdup("Aruba"));
	dictionary_insert(alpha2_to_name, strdup("AU"), strdup("Australia"));
	dictionary_insert(alpha2_to_name, strdup("AT"), strdup("Austria"));
	dictionary_insert(alpha2_to_name, strdup("AZ"), strdup("Azerbaijan"));
	dictionary_insert(alpha2_to_name, strdup("BS"), strdup("Bahamas"));
	dictionary_insert(alpha2_to_name, strdup("BH"), strdup("Bahrain"));
	dictionary_insert(alpha2_to_name, strdup("BD"), strdup("Bangladesh"));
	dictionary_insert(alpha2_to_name, strdup("BB"), strdup("Barbados"));
	dictionary_insert(alpha2_to_name, strdup("BY"), strdup("Belarus"));
	dictionary_insert(alpha2_to_name, strdup("BE"), strdup("Belgium"));
	dictionary_insert(alpha2_to_name, strdup("BZ"), strdup("Belize"));
	dictionary_insert(alpha2_to_name, strdup("BJ"), strdup("Benin"));
	dictionary_insert(alpha2_to_name, strdup("BM"), strdup("Bermuda"));
	dictionary_insert(alpha2_to_name, strdup("BT"), strdup("Bhutan"));
	dictionary_insert(alpha2_to_name, strdup("BO"), strdup("Bolivia (Plurinational State of)"));
	dictionary_insert(alpha2_to_name, strdup("BQ"), strdup("Bonaire, Sint Eustatius and Saba"));
	dictionary_insert(alpha2_to_name, strdup("BA"), strdup("Bosnia and Herzegovina"));
	dictionary_insert(alpha2_to_name, strdup("BW"), strdup("Botswana"));
	dictionary_insert(alpha2_to_name, strdup("BV"), strdup("Bouvet Island"));
	dictionary_insert(alpha2_to_name, strdup("BR"), strdup("Brazil"));
	dictionary_insert(alpha2_to_name, strdup("IO"), strdup("British Indian Ocean Territory"));
	dictionary_insert(alpha2_to_name, strdup("BN"), strdup("Brunei Darussalam"));
	dictionary_insert(alpha2_to_name, strdup("BG"), strdup("Bulgaria"));
	dictionary_insert(alpha2_to_name, strdup("BF"), strdup("Burkina Faso"));
	dictionary_insert(alpha2_to_name, strdup("BI"), strdup("Burundi"));
	dictionary_insert(alpha2_to_name, strdup("CV"), strdup("Cabo Verde"));
	dictionary_insert(alpha2_to_name, strdup("KH"), strdup("Cambodia"));
	dictionary_insert(alpha2_to_name, strdup("CM"), strdup("Cameroon"));
	dictionary_insert(alpha2_to_name, strdup("CA"), strdup("Canada"));
	dictionary_insert(alpha2_to_name, strdup("KY"), strdup("Cayman Islands"));
	dictionary_insert(alpha2_to_name, strdup("CF"), strdup("Central African Republic"));
	dictionary_insert(alpha2_to_name, strdup("TD"), strdup("Chad"));
	dictionary_insert(alpha2_to_name, strdup("CL"), strdup("Chile"));
	dictionary_insert(alpha2_to_name, strdup("CN"), strdup("China"));
	dictionary_insert(alpha2_to_name, strdup("CX"), strdup("Christmas Island"));
	dictionary_insert(alpha2_to_name, strdup("CC"), strdup("Cocos (Keeling) Islands"));
	dictionary_insert(alpha2_to_name, strdup("CO"), strdup("Colombia"));
	dictionary_insert(alpha2_to_name, strdup("KM"), strdup("Comoros"));
	dictionary_insert(alpha2_to_name, strdup("CG"), strdup("Congo"));
	dictionary_insert(alpha2_to_name, strdup("CD"), strdup("Congo, Democratic Republic of the"));
	dictionary_insert(alpha2_to_name, strdup("CK"), strdup("Cook Islands"));
	dictionary_insert(alpha2_to_name, strdup("CR"), strdup("Costa Rica"));
	dictionary_insert(alpha2_to_name, strdup("CI"), strdup("Côte d'Ivoire"));
	dictionary_insert(alpha2_to_name, strdup("HR"), strdup("Croatia"));
	dictionary_insert(alpha2_to_name, strdup("CU"), strdup("Cuba"));
	dictionary_insert(alpha2_to_name, strdup("CW"), strdup("Curaçao"));
	dictionary_insert(alpha2_to_name, strdup("CY"), strdup("Cyprus"));
	dictionary_insert(alpha2_to_name, strdup("CZ"), strdup("Czechia"));
	dictionary_insert(alpha2_to_name, strdup("DK"), strdup("Denmark"));
	dictionary_insert(alpha2_to_name, strdup("DJ"), strdup("Djibouti"));
	dictionary_insert(alpha2_to_name, strdup("DM"), strdup("Dominica"));
	dictionary_insert(alpha2_to_name, strdup("DO"), strdup("Dominican Republic"));
	dictionary_insert(alpha2_to_name, strdup("EC"), strdup("Ecuador"));
	dictionary_insert(alpha2_to_name, strdup("EG"), strdup("Egypt"));
	dictionary_insert(alpha2_to_name, strdup("SV"), strdup("El Salvador"));
	dictionary_insert(alpha2_to_name, strdup("GQ"), strdup("Equatorial Guinea"));
	dictionary_insert(alpha2_to_name, strdup("ER"), strdup("Eritrea"));
	dictionary_insert(alpha2_to_name, strdup("EE"), strdup("Estonia"));
	dictionary_insert(alpha2_to_name, strdup("SZ"), strdup("Eswatini"));
	dictionary_insert(alpha2_to_name, strdup("ET"), strdup("Ethiopia"));
	dictionary_insert(alpha2_to_name, strdup("FK"), strdup("Falkland Islands (Malvinas)"));
	dictionary_insert(alpha2_to_name, strdup("FO"), strdup("Faroe Islands"));
	dictionary_insert(alpha2_to_name, strdup("FJ"), strdup("Fiji"));
	dictionary_insert(alpha2_to_name, strdup("FI"), strdup("Finland"));
	dictionary_insert(alpha2_to_name, strdup("FR"), strdup("France"));
	dictionary_insert(alpha2_to_name, strdup("GF"), strdup("French Guiana"));
	dictionary_insert(alpha2_to_name, strdup("PF"), strdup("French Polynesia"));
	dictionary_insert(alpha2_to_name, strdup("TF"), strdup("French Southern Territories"));
	dictionary_insert(alpha2_to_name, strdup("GA"), strdup("Gabon"));
	dictionary_insert(alpha2_to_name, strdup("GM"), strdup("Gambia"));
	dictionary_insert(alpha2_to_name, strdup("GE"), strdup("Georgia"));
	dictionary_insert(alpha2_to_name, strdup("DE"), strdup("Germany"));
	dictionary_insert(alpha2_to_name, strdup("GH"), strdup("Ghana"));
	dictionary_insert(alpha2_to_name, strdup("GI"), strdup("Gibraltar"));
	dictionary_insert(alpha2_to_name, strdup("GR"), strdup("Greece"));
	dictionary_insert(alpha2_to_name, strdup("GL"), strdup("Greenland"));
	dictionary_insert(alpha2_to_name, strdup("GD"), strdup("Grenada"));
	dictionary_insert(alpha2_to_name, strdup("GP"), strdup("Guadeloupe"));
	dictionary_insert(alpha2_to_name, strdup("GU"), strdup("Guam"));
	dictionary_insert(alpha2_to_name, strdup("GT"), strdup("Guatemala"));
	dictionary_insert(alpha2_to_name, strdup("GG"), strdup("Guernsey"));
	dictionary_insert(alpha2_to_name, strdup("GN"), strdup("Guinea"));
	dictionary_insert(alpha2_to_name, strdup("GW"), strdup("Guinea-Bissau"));
	dictionary_insert(alpha2_to_name, strdup("GY"), strdup("Guyana"));
	dictionary_insert(alpha2_to_name, strdup("HT"), strdup("Haiti"));
	dictionary_insert(alpha2_to_name, strdup("HM"), strdup("Heard Island and McDonald Islands"));
	dictionary_insert(alpha2_to_name, strdup("VA"), strdup("Holy See"));
	dictionary_insert(alpha2_to_name, strdup("HN"), strdup("Honduras"));
	dictionary_insert(alpha2_to_name, strdup("HK"), strdup("Hong Kong"));
	dictionary_insert(alpha2_to_name, strdup("HU"), strdup("Hungary"));
	dictionary_insert(alpha2_to_name, strdup("IS"), strdup("Iceland"));
	dictionary_insert(alpha2_to_name, strdup("IN"), strdup("India"));
	dictionary_insert(alpha2_to_name, strdup("ID"), strdup("Indonesia"));
	dictionary_insert(alpha2_to_name, strdup("IR"), strdup("Iran (Islamic Republic of)"));
	dictionary_insert(alpha2_to_name, strdup("IQ"), strdup("Iraq"));
	dictionary_insert(alpha2_to_name, strdup("IE"), strdup("Ireland"));
	dictionary_insert(alpha2_to_name, strdup("IM"), strdup("Isle of Man"));
	dictionary_insert(alpha2_to_name, strdup("IL"), strdup("Israel"));
	dictionary_insert(alpha2_to_name, strdup("IT"), strdup("Italy"));
	dictionary_insert(alpha2_to_name, strdup("JM"), strdup("Jamaica"));
	dictionary_insert(alpha2_to_name, strdup("JP"), strdup("Japan"));
	dictionary_insert(alpha2_to_name, strdup("JE"), strdup("Jersey"));
	dictionary_insert(alpha2_to_name, strdup("JO"), strdup("Jordan"));
	dictionary_insert(alpha2_to_name, strdup("KZ"), strdup("Kazakhstan"));
	dictionary_insert(alpha2_to_name, strdup("KE"), strdup("Kenya"));
	dictionary_insert(alpha2_to_name, strdup("KI"), strdup("Kiribati"));
	dictionary_insert(alpha2_to_name, strdup("KP"), strdup("Korea (Democratic People's Republic of)"));
	dictionary_insert(alpha2_to_name, strdup("KR"), strdup("Korea, Republic of"));
	dictionary_insert(alpha2_to_name, strdup("KW"), strdup("Kuwait"));
	dictionary_insert(alpha2_to_name, strdup("KG"), strdup("Kyrgyzstan"));
	dictionary_insert(alpha2_to_name, strdup("LA"), strdup("Lao People's Democratic Republic"));
	dictionary_insert(alpha2_to_name, strdup("LV"), strdup("Latvia"));
	dictionary_insert(alpha2_to_name, strdup("LB"), strdup("Lebanon"));
	dictionary_insert(alpha2_to_name, strdup("LS"), strdup("Lesotho"));
	dictionary_insert(alpha2_to_name, strdup("LR"), strdup("Liberia"));
	dictionary_insert(alpha2_to_name, strdup("LY"), strdup("Libya"));
	dictionary_insert(alpha2_to_name, strdup("LI"), strdup("Liechtenstein"));
	dictionary_insert(alpha2_to_name, strdup("LT"), strdup("Lithuania"));
	dictionary_insert(alpha2_to_name, strdup("LU"), strdup("Luxembourg"));
	dictionary_insert(alpha2_to_name, strdup("MO"), strdup("Macao"));
	dictionary_insert(alpha2_to_name, strdup("MG"), strdup("Madagascar"));
	dictionary_insert(alpha2_to_name, strdup("MW"), strdup("Malawi"));
	dictionary_insert(alpha2_to_name, strdup("MY"), strdup("Malaysia"));
	dictionary_insert(alpha2_to_name, strdup("MV"), strdup("Maldives"));
	dictionary_insert(alpha2_to_name, strdup("ML"), strdup("Mali"));
	dictionary_insert(alpha2_to_name, strdup("MT"), strdup("Malta"));
	dictionary_insert(alpha2_to_name, strdup("MH"), strdup("Marshall Islands"));
	dictionary_insert(alpha2_to_name, strdup("MQ"), strdup("Martinique"));
	dictionary_insert(alpha2_to_name, strdup("MR"), strdup("Mauritania"));
	dictionary_insert(alpha2_to_name, strdup("MU"), strdup("Mauritius"));
	dictionary_insert(alpha2_to_name, strdup("YT"), strdup("Mayotte"));
	dictionary_insert(alpha2_to_name, strdup("MX"), strdup("Mexico"));
	dictionary_insert(alpha2_to_name, strdup("FM"), strdup("Micronesia (Federated States of)"));
	dictionary_insert(alpha2_to_name, strdup("MD"), strdup("Moldova, Republic of"));
	dictionary_insert(alpha2_to_name, strdup("MC"), strdup("Monaco"));
	dictionary_insert(alpha2_to_name, strdup("MN"), strdup("Mongolia"));
	dictionary_insert(alpha2_to_name, strdup("ME"), strdup("Montenegro"));
	dictionary_insert(alpha2_to_name, strdup("MS"), strdup("Montserrat"));
	dictionary_insert(alpha2_to_name, strdup("MA"), strdup("Morocco"));
	dictionary_insert(alpha2_to_name, strdup("MZ"), strdup("Mozambique"));
	dictionary_insert(alpha2_to_name, strdup("MM"), strdup("Myanmar"));
	dictionary_insert(alpha2_to_name, strdup("NA"), strdup("Namibia"));
	dictionary_insert(alpha2_to_name, strdup("NR"), strdup("Nauru"));
	dictionary_insert(alpha2_to_name, strdup("NP"), strdup("Nepal"));
	dictionary_insert(alpha2_to_name, strdup("NL"), strdup("Netherlands"));
	dictionary_insert(alpha2_to_name, strdup("NC"), strdup("New Caledonia"));
	dictionary_insert(alpha2_to_name, strdup("NZ"), strdup("New Zealand"));
	dictionary_insert(alpha2_to_name, strdup("NI"), strdup("Nicaragua"));
	dictionary_insert(alpha2_to_name, strdup("NE"), strdup("Niger"));
	dictionary_insert(alpha2_to_name, strdup("NG"), strdup("Nigeria"));
	dictionary_insert(alpha2_to_name, strdup("NU"), strdup("Niue"));
	dictionary_insert(alpha2_to_name, strdup("NF"), strdup("Norfolk Island"));
	dictionary_insert(alpha2_to_name, strdup("MK"), strdup("North Macedonia"));
	dictionary_insert(alpha2_to_name, strdup("MP"), strdup("Northern Mariana Islands"));
	dictionary_insert(alpha2_to_name, strdup("NO"), strdup("Norway"));
	dictionary_insert(alpha2_to_name, strdup("OM"), strdup("Oman"));
	dictionary_insert(alpha2_to_name, strdup("PK"), strdup("Pakistan"));
	dictionary_insert(alpha2_to_name, strdup("PW"), strdup("Palau"));
	dictionary_insert(alpha2_to_name, strdup("PS"), strdup("Palestine, State of"));
	dictionary_insert(alpha2_to_name, strdup("PA"), strdup("Panama"));
	dictionary_insert(alpha2_to_name, strdup("PG"), strdup("Papua New Guinea"));
	dictionary_insert(alpha2_to_name, strdup("PY"), strdup("Paraguay"));
	dictionary_insert(alpha2_to_name, strdup("PE"), strdup("Peru"));
	dictionary_insert(alpha2_to_name, strdup("PH"), strdup("Philippines"));
	dictionary_insert(alpha2_to_name, strdup("PN"), strdup("Pitcairn"));
	dictionary_insert(alpha2_to_name, strdup("PL"), strdup("Poland"));
	dictionary_insert(alpha2_to_name, strdup("PT"), strdup("Portugal"));
	dictionary_insert(alpha2_to_name, strdup("PR"), strdup("Puerto Rico"));
	dictionary_insert(alpha2_to_name, strdup("QA"), strdup("Qatar"));
	dictionary_insert(alpha2_to_name, strdup("RE"), strdup("Réunion"));
	dictionary_insert(alpha2_to_name, strdup("RO"), strdup("Romania"));
	dictionary_insert(alpha2_to_name, strdup("RU"), strdup("Russian Federation"));
	dictionary_insert(alpha2_to_name, strdup("RW"), strdup("Rwanda"));
	dictionary_insert(alpha2_to_name, strdup("BL"), strdup("Saint Barthélemy"));
	dictionary_insert(alpha2_to_name, strdup("SH"), strdup("Saint Helena, Ascension and Tristan da Cunha"));
	dictionary_insert(alpha2_to_name, strdup("KN"), strdup("Saint Kitts and Nevis"));
	dictionary_insert(alpha2_to_name, strdup("LC"), strdup("Saint Lucia"));
	dictionary_insert(alpha2_to_name, strdup("MF"), strdup("Saint Martin (French part)"));
	dictionary_insert(alpha2_to_name, strdup("PM"), strdup("Saint Pierre and Miquelon"));
	dictionary_insert(alpha2_to_name, strdup("VC"), strdup("Saint Vincent and the Grenadines"));
	dictionary_insert(alpha2_to_name, strdup("WS"), strdup("Samoa"));
	dictionary_insert(alpha2_to_name, strdup("SM"), strdup("San Marino"));
	dictionary_insert(alpha2_to_name, strdup("ST"), strdup("Sao Tome and Principe"));
	dictionary_insert(alpha2_to_name, strdup("SA"), strdup("Saudi Arabia"));
	dictionary_insert(alpha2_to_name, strdup("SN"), strdup("Senegal"));
	dictionary_insert(alpha2_to_name, strdup("RS"), strdup("Serbia"));
	dictionary_insert(alpha2_to_name, strdup("SC"), strdup("Seychelles"));
	dictionary_insert(alpha2_to_name, strdup("SL"), strdup("Sierra Leone"));
	dictionary_insert(alpha2_to_name, strdup("SG"), strdup("Singapore"));
	dictionary_insert(alpha2_to_name, strdup("SX"), strdup("Sint Maarten (Dutch part)"));
	dictionary_insert(alpha2_to_name, strdup("SK"), strdup("Slovakia"));
	dictionary_insert(alpha2_to_name, strdup("SI"), strdup("Slovenia"));
	dictionary_insert(alpha2_to_name, strdup("SB"), strdup("Solomon Islands"));
	dictionary_insert(alpha2_to_name, strdup("SO"), strdup("Somalia"));
	dictionary_insert(alpha2_to_name, strdup("ZA"), strdup("South Africa"));
	dictionary_insert(alpha2_to_name, strdup("GS"), strdup("South Georgia and the South Sandwich Islands"));
	dictionary_insert(alpha2_to_name, strdup("SS"), strdup("South Sudan"));
	dictionary_insert(alpha2_to_name, strdup("ES"), strdup("Spain"));
	dictionary_insert(alpha2_to_name, strdup("LK"), strdup("Sri Lanka"));
	dictionary_insert(alpha2_to_name, strdup("SD"), strdup("Sudan"));
	dictionary_insert(alpha2_to_name, strdup("SR"), strdup("Suriname"));
	dictionary_insert(alpha2_to_name, strdup("SJ"), strdup("Svalbard and Jan Mayen"));
	dictionary_insert(alpha2_to_name, strdup("SE"), strdup("Sweden"));
	dictionary_insert(alpha2_to_name, strdup("CH"), strdup("Switzerland"));
	dictionary_insert(alpha2_to_name, strdup("SY"), strdup("Syrian Arab Republic"));
	dictionary_insert(alpha2_to_name, strdup("TW"), strdup("Taiwan, Province of China"));
	dictionary_insert(alpha2_to_name, strdup("TJ"), strdup("Tajikistan"));
	dictionary_insert(alpha2_to_name, strdup("TZ"), strdup("Tanzania, United Republic of"));
	dictionary_insert(alpha2_to_name, strdup("TH"), strdup("Thailand"));
	dictionary_insert(alpha2_to_name, strdup("TL"), strdup("Timor-Leste"));
	dictionary_insert(alpha2_to_name, strdup("TG"), strdup("Togo"));
	dictionary_insert(alpha2_to_name, strdup("TK"), strdup("Tokelau"));
	dictionary_insert(alpha2_to_name, strdup("TO"), strdup("Tonga"));
	dictionary_insert(alpha2_to_name, strdup("TT"), strdup("Trinidad and Tobago"));
	dictionary_insert(alpha2_to_name, strdup("TN"), strdup("Tunisia"));
	dictionary_insert(alpha2_to_name, strdup("TR"), strdup("Turkey"));
	dictionary_insert(alpha2_to_name, strdup("TM"), strdup("Turkmenistan"));
	dictionary_insert(alpha2_to_name, strdup("TC"), strdup("Turks and Caicos Islands"));
	dictionary_insert(alpha2_to_name, strdup("TV"), strdup("Tuvalu"));
	dictionary_insert(alpha2_to_name, strdup("UG"), strdup("Uganda"));
	dictionary_insert(alpha2_to_name, strdup("UA"), strdup("Ukraine"));
	dictionary_insert(alpha2_to_name, strdup("AE"), strdup("United Arab Emirates"));
	dictionary_insert(alpha2_to_name, strdup("GB"), strdup("United Kingdom of Great Britain and Northern Ireland"));
	dictionary_insert(alpha2_to_name, strdup("US"), strdup("United States of America"));
	dictionary_insert(alpha2_to_name, strdup("UM"), strdup("United States Minor Outlying Islands"));
	dictionary_insert(alpha2_to_name, strdup("UY"), strdup("Uruguay"));
	dictionary_insert(alpha2_to_name, strdup("UZ"), strdup("Uzbekistan"));
	dictionary_insert(alpha2_to_name, strdup("VU"), strdup("Vanuatu"));
	dictionary_insert(alpha2_to_name, strdup("VE"), strdup("Venezuela (Bolivarian Republic of)"));
	dictionary_insert(alpha2_to_name, strdup("VN"), strdup("Viet Nam"));
	dictionary_insert(alpha2_to_name, strdup("VG"), strdup("Virgin Islands (British)"));
	dictionary_insert(alpha2_to_name, strdup("VI"), strdup("Virgin Islands (U.S.)"));
	dictionary_insert(alpha2_to_name, strdup("WF"), strdup("Wallis and Futuna"));
	dictionary_insert(alpha2_to_name, strdup("EH"), strdup("Western Sahara"));
	dictionary_insert(alpha2_to_name, strdup("YE"), strdup("Yemen"));
	dictionary_insert(alpha2_to_name, strdup("ZM"), strdup("Zambia"));
	dictionary_insert(alpha2_to_name, strdup("ZW"), strdup("Zimbabwe"));
	
	// Create a dictionary mapping alpha2 to numeric

	// Create a vertex for each country
	struct Vertex * country_AF = construct_vertex(4, "AF");
	struct Vertex * country_AX = construct_vertex(248, "AX");
	struct Vertex * country_AL = construct_vertex(8, "AL");
	struct Vertex * country_DZ = construct_vertex(12, "DZ");
	struct Vertex * country_AS = construct_vertex(16, "AS");
	struct Vertex * country_AD = construct_vertex(20, "AD");
	struct Vertex * country_AO = construct_vertex(24, "AO");
	struct Vertex * country_AI = construct_vertex(660, "AI");
	struct Vertex * country_AQ = construct_vertex(10, "AQ");
	struct Vertex * country_AG = construct_vertex(28, "AG");
	struct Vertex * country_AR = construct_vertex(32, "AR");
	struct Vertex * country_AM = construct_vertex(51, "AM");
	struct Vertex * country_AW = construct_vertex(533, "AW");
	struct Vertex * country_AU = construct_vertex(36, "AU");
	struct Vertex * country_AT = construct_vertex(40, "AT");
	struct Vertex * country_AZ = construct_vertex(31, "AZ");
	struct Vertex * country_BS = construct_vertex(44, "BS");
	struct Vertex * country_BH = construct_vertex(48, "BH");
	struct Vertex * country_BD = construct_vertex(50, "BD");
	struct Vertex * country_BB = construct_vertex(52, "BB");
	struct Vertex * country_BY = construct_vertex(112, "BY");
	struct Vertex * country_BE = construct_vertex(56, "BE");
	struct Vertex * country_BZ = construct_vertex(84, "BZ");
	struct Vertex * country_BJ = construct_vertex(204, "BJ");
	struct Vertex * country_BM = construct_vertex(60, "BM");
	struct Vertex * country_BT = construct_vertex(64, "BT");
	struct Vertex * country_BO = construct_vertex(68, "BO");
	struct Vertex * country_BQ = construct_vertex(535, "BQ");
	struct Vertex * country_BA = construct_vertex(70, "BA");
	struct Vertex * country_BW = construct_vertex(72, "BW");
	struct Vertex * country_BV = construct_vertex(74, "BV");
	struct Vertex * country_BR = construct_vertex(76, "BR");
	struct Vertex * country_IO = construct_vertex(86, "IO");
	struct Vertex * country_BN = construct_vertex(96, "BN");
	struct Vertex * country_BG = construct_vertex(100, "BG");
	struct Vertex * country_BF = construct_vertex(854, "BF");
	struct Vertex * country_BI = construct_vertex(108, "BI");
	struct Vertex * country_CV = construct_vertex(132, "CV");
	struct Vertex * country_KH = construct_vertex(116, "KH");
	struct Vertex * country_CM = construct_vertex(120, "CM");
	struct Vertex * country_CA = construct_vertex(124, "CA");
	struct Vertex * country_KY = construct_vertex(136, "KY");
	struct Vertex * country_CF = construct_vertex(140, "CF");
	struct Vertex * country_TD = construct_vertex(148, "TD");
	struct Vertex * country_CL = construct_vertex(152, "CL");
	struct Vertex * country_CN = construct_vertex(156, "CN");
	struct Vertex * country_CX = construct_vertex(162, "CX");
	struct Vertex * country_CC = construct_vertex(166, "CC");
	struct Vertex * country_CO = construct_vertex(170, "CO");
	struct Vertex * country_KM = construct_vertex(174, "KM");
	struct Vertex * country_CG = construct_vertex(178, "CG");
	struct Vertex * country_CD = construct_vertex(180, "CD");
	struct Vertex * country_CK = construct_vertex(184, "CK");
	struct Vertex * country_CR = construct_vertex(188, "CR");
	struct Vertex * country_CI = construct_vertex(384, "CI");
	struct Vertex * country_HR = construct_vertex(191, "HR");
	struct Vertex * country_CU = construct_vertex(192, "CU");
	struct Vertex * country_CW = construct_vertex(531, "CW");
	struct Vertex * country_CY = construct_vertex(196, "CY");
	struct Vertex * country_CZ = construct_vertex(203, "CZ");
	struct Vertex * country_DK = construct_vertex(208, "DK");
	struct Vertex * country_DJ = construct_vertex(262, "DJ");
	struct Vertex * country_DM = construct_vertex(212, "DM");
	struct Vertex * country_DO = construct_vertex(214, "DO");
	struct Vertex * country_EC = construct_vertex(218, "EC");
	struct Vertex * country_EG = construct_vertex(818, "EG");
	struct Vertex * country_SV = construct_vertex(222, "SV");
	struct Vertex * country_GQ = construct_vertex(226, "GQ");
	struct Vertex * country_ER = construct_vertex(232, "ER");
	struct Vertex * country_EE = construct_vertex(233, "EE");
	struct Vertex * country_SZ = construct_vertex(748, "SZ");
	struct Vertex * country_ET = construct_vertex(231, "ET");
	struct Vertex * country_FK = construct_vertex(238, "FK");
	struct Vertex * country_FO = construct_vertex(234, "FO");
	struct Vertex * country_FJ = construct_vertex(242, "FJ");
	struct Vertex * country_FI = construct_vertex(246, "FI");
	struct Vertex * country_FR = construct_vertex(250, "FR");
	struct Vertex * country_GF = construct_vertex(254, "GF");
	struct Vertex * country_PF = construct_vertex(258, "PF");
	struct Vertex * country_TF = construct_vertex(260, "TF");
	struct Vertex * country_GA = construct_vertex(266, "GA");
	struct Vertex * country_GM = construct_vertex(270, "GM");
	struct Vertex * country_GE = construct_vertex(268, "GE");
	struct Vertex * country_DE = construct_vertex(276, "DE");
	struct Vertex * country_GH = construct_vertex(288, "GH");
	struct Vertex * country_GI = construct_vertex(292, "GI");
	struct Vertex * country_GR = construct_vertex(300, "GR");
	struct Vertex * country_GL = construct_vertex(304, "GL");
	struct Vertex * country_GD = construct_vertex(308, "GD");
	struct Vertex * country_GP = construct_vertex(312, "GP");
	struct Vertex * country_GU = construct_vertex(316, "GU");
	struct Vertex * country_GT = construct_vertex(320, "GT");
	struct Vertex * country_GG = construct_vertex(831, "GG");
	struct Vertex * country_GN = construct_vertex(324, "GN");
	struct Vertex * country_GW = construct_vertex(624, "GW");
	struct Vertex * country_GY = construct_vertex(328, "GY");
	struct Vertex * country_HT = construct_vertex(332, "HT");
	struct Vertex * country_HM = construct_vertex(334, "HM");
	struct Vertex * country_VA = construct_vertex(336, "VA");
	struct Vertex * country_HN = construct_vertex(340, "HN");
	struct Vertex * country_HK = construct_vertex(344, "HK");
	struct Vertex * country_HU = construct_vertex(348, "HU");
	struct Vertex * country_IS = construct_vertex(352, "IS");
	struct Vertex * country_IN = construct_vertex(356, "IN");
	struct Vertex * country_ID = construct_vertex(360, "ID");
	struct Vertex * country_IR = construct_vertex(364, "IR");
	struct Vertex * country_IQ = construct_vertex(368, "IQ");
	struct Vertex * country_IE = construct_vertex(372, "IE");
	struct Vertex * country_IM = construct_vertex(833, "IM");
	struct Vertex * country_IL = construct_vertex(376, "IL");
	struct Vertex * country_IT = construct_vertex(380, "IT");
	struct Vertex * country_JM = construct_vertex(388, "JM");
	struct Vertex * country_JP = construct_vertex(392, "JP");
	struct Vertex * country_JE = construct_vertex(832, "JE");
	struct Vertex * country_JO = construct_vertex(400, "JO");
	struct Vertex * country_KZ = construct_vertex(398, "KZ");
	struct Vertex * country_KE = construct_vertex(404, "KE");
	struct Vertex * country_KI = construct_vertex(296, "KI");
	struct Vertex * country_KP = construct_vertex(408, "KP");
	struct Vertex * country_KR = construct_vertex(410, "KR");
	struct Vertex * country_KW = construct_vertex(414, "KW");
	struct Vertex * country_KG = construct_vertex(417, "KG");
	struct Vertex * country_LA = construct_vertex(418, "LA");
	struct Vertex * country_LV = construct_vertex(428, "LV");
	struct Vertex * country_LB = construct_vertex(422, "LB");
	struct Vertex * country_LS = construct_vertex(426, "LS");
	struct Vertex * country_LR = construct_vertex(430, "LR");
	struct Vertex * country_LY = construct_vertex(434, "LY");
	struct Vertex * country_LI = construct_vertex(438, "LI");
	struct Vertex * country_LT = construct_vertex(440, "LT");
	struct Vertex * country_LU = construct_vertex(442, "LU");
	struct Vertex * country_MO = construct_vertex(446, "MO");
	struct Vertex * country_MG = construct_vertex(450, "MG");
	struct Vertex * country_MW = construct_vertex(454, "MW");
	struct Vertex * country_MY = construct_vertex(458, "MY");
	struct Vertex * country_MV = construct_vertex(462, "MV");
	struct Vertex * country_ML = construct_vertex(466, "ML");
	struct Vertex * country_MT = construct_vertex(470, "MT");
	struct Vertex * country_MH = construct_vertex(584, "MH");
	struct Vertex * country_MQ = construct_vertex(474, "MQ");
	struct Vertex * country_MR = construct_vertex(478, "MR");
	struct Vertex * country_MU = construct_vertex(480, "MU");
	struct Vertex * country_YT = construct_vertex(175, "YT");
	struct Vertex * country_MX = construct_vertex(484, "MX");
	struct Vertex * country_FM = construct_vertex(583, "FM");
	struct Vertex * country_MD = construct_vertex(498, "MD");
	struct Vertex * country_MC = construct_vertex(492, "MC");
	struct Vertex * country_MN = construct_vertex(496, "MN");
	struct Vertex * country_ME = construct_vertex(499, "ME");
	struct Vertex * country_MS = construct_vertex(500, "MS");
	struct Vertex * country_MA = construct_vertex(504, "MA");
	struct Vertex * country_MZ = construct_vertex(508, "MZ");
	struct Vertex * country_MM = construct_vertex(104, "MM");
	struct Vertex * country_NA = construct_vertex(516, "NA");
	struct Vertex * country_NR = construct_vertex(520, "NR");
	struct Vertex * country_NP = construct_vertex(524, "NP");
	struct Vertex * country_NL = construct_vertex(528, "NL");
	struct Vertex * country_NC = construct_vertex(540, "NC");
	struct Vertex * country_NZ = construct_vertex(554, "NZ");
	struct Vertex * country_NI = construct_vertex(558, "NI");
	struct Vertex * country_NE = construct_vertex(562, "NE");
	struct Vertex * country_NG = construct_vertex(566, "NG");
	struct Vertex * country_NU = construct_vertex(570, "NU");
	struct Vertex * country_NF = construct_vertex(574, "NF");
	struct Vertex * country_MK = construct_vertex(807, "MK");
	struct Vertex * country_MP = construct_vertex(580, "MP");
	struct Vertex * country_NO = construct_vertex(578, "NO");
	struct Vertex * country_OM = construct_vertex(512, "OM");
	struct Vertex * country_PK = construct_vertex(586, "PK");
	struct Vertex * country_PW = construct_vertex(585, "PW");
	struct Vertex * country_PS = construct_vertex(275, "PS");
	struct Vertex * country_PA = construct_vertex(591, "PA");
	struct Vertex * country_PG = construct_vertex(598, "PG");
	struct Vertex * country_PY = construct_vertex(600, "PY");
	struct Vertex * country_PE = construct_vertex(604, "PE");
	struct Vertex * country_PH = construct_vertex(608, "PH");
	struct Vertex * country_PN = construct_vertex(612, "PN");
	struct Vertex * country_PL = construct_vertex(616, "PL");
	struct Vertex * country_PT = construct_vertex(620, "PT");
	struct Vertex * country_PR = construct_vertex(630, "PR");
	struct Vertex * country_QA = construct_vertex(634, "QA");
	struct Vertex * country_RE = construct_vertex(638, "RE");
	struct Vertex * country_RO = construct_vertex(642, "RO");
	struct Vertex * country_RU = construct_vertex(643, "RU");
	struct Vertex * country_RW = construct_vertex(646, "RW");
	struct Vertex * country_BL = construct_vertex(652, "BL");
	struct Vertex * country_SH = construct_vertex(654, "SH");
	struct Vertex * country_KN = construct_vertex(659, "KN");
	struct Vertex * country_LC = construct_vertex(662, "LC");
	struct Vertex * country_MF = construct_vertex(663, "MF");
	struct Vertex * country_PM = construct_vertex(666, "PM");
	struct Vertex * country_VC = construct_vertex(670, "VC");
	struct Vertex * country_WS = construct_vertex(882, "WS");
	struct Vertex * country_SM = construct_vertex(674, "SM");
	struct Vertex * country_ST = construct_vertex(678, "ST");
	struct Vertex * country_SA = construct_vertex(682, "SA");
	struct Vertex * country_SN = construct_vertex(686, "SN");
	struct Vertex * country_RS = construct_vertex(688, "RS");
	struct Vertex * country_SC = construct_vertex(690, "SC");
	struct Vertex * country_SL = construct_vertex(694, "SL");
	struct Vertex * country_SG = construct_vertex(702, "SG");
	struct Vertex * country_SX = construct_vertex(534, "SX");
	struct Vertex * country_SK = construct_vertex(703, "SK");
	struct Vertex * country_SI = construct_vertex(705, "SI");
	struct Vertex * country_SB = construct_vertex(90, "SB");
	struct Vertex * country_SO = construct_vertex(706, "SO");
	struct Vertex * country_ZA = construct_vertex(710, "ZA");
	struct Vertex * country_GS = construct_vertex(239, "GS");
	struct Vertex * country_SS = construct_vertex(728, "SS");
	struct Vertex * country_ES = construct_vertex(724, "ES");
	struct Vertex * country_LK = construct_vertex(144, "LK");
	struct Vertex * country_SD = construct_vertex(729, "SD");
	struct Vertex * country_SR = construct_vertex(740, "SR");
	struct Vertex * country_SJ = construct_vertex(744, "SJ");
	struct Vertex * country_SE = construct_vertex(752, "SE");
	struct Vertex * country_CH = construct_vertex(756, "CH");
	struct Vertex * country_SY = construct_vertex(760, "SY");
	struct Vertex * country_TW = construct_vertex(158, "TW");
	struct Vertex * country_TJ = construct_vertex(762, "TJ");
	struct Vertex * country_TZ = construct_vertex(834, "TZ");
	struct Vertex * country_TH = construct_vertex(764, "TH");
	struct Vertex * country_TL = construct_vertex(626, "TL");
	struct Vertex * country_TG = construct_vertex(768, "TG");
	struct Vertex * country_TK = construct_vertex(772, "TK");
	struct Vertex * country_TO = construct_vertex(776, "TO");
	struct Vertex * country_TT = construct_vertex(780, "TT");
	struct Vertex * country_TN = construct_vertex(788, "TN");
	struct Vertex * country_TR = construct_vertex(792, "TR");
	struct Vertex * country_TM = construct_vertex(795, "TM");
	struct Vertex * country_TC = construct_vertex(796, "TC");
	struct Vertex * country_TV = construct_vertex(798, "TV");
	struct Vertex * country_UG = construct_vertex(800, "UG");
	struct Vertex * country_UA = construct_vertex(804, "UA");
	struct Vertex * country_AE = construct_vertex(784, "AE");
	struct Vertex * country_GB = construct_vertex(826, "GB");
	struct Vertex * country_US = construct_vertex(840, "US");
	struct Vertex * country_UM = construct_vertex(581, "UM");
	struct Vertex * country_UY = construct_vertex(858, "UY");
	struct Vertex * country_UZ = construct_vertex(860, "UZ");
	struct Vertex * country_VU = construct_vertex(548, "VU");
	struct Vertex * country_VE = construct_vertex(862, "VE");
	struct Vertex * country_VN = construct_vertex(704, "VN");
	struct Vertex * country_VG = construct_vertex(92, "VG");
	struct Vertex * country_VI = construct_vertex(850, "VI");
	struct Vertex * country_WF = construct_vertex(876, "WF");
	struct Vertex * country_EH = construct_vertex(732, "EH");
	struct Vertex * country_YE = construct_vertex(887, "YE");
	struct Vertex * country_ZM = construct_vertex(894, "ZM");
	struct Vertex * country_ZW = construct_vertex(716, "ZW");

	// Array that lets us access the codes
	struct Vertex * countryVertices[895];
	countryVertices[4] = country_AF;
	countryVertices[248] = country_AX;
	countryVertices[8] = country_AL;
	countryVertices[12] = country_DZ;
	countryVertices[16] = country_AS;
	countryVertices[20] = country_AD;
	countryVertices[24] = country_AO;
	countryVertices[660] = country_AI;
	countryVertices[10] = country_AQ;
	countryVertices[28] = country_AG;
	countryVertices[32] = country_AR;
	countryVertices[51] = country_AM;
	countryVertices[533] = country_AW;
	countryVertices[36] = country_AU;
	countryVertices[40] = country_AT;
	countryVertices[31] = country_AZ;
	countryVertices[44] = country_BS;
	countryVertices[48] = country_BH;
	countryVertices[50] = country_BD;
	countryVertices[52] = country_BB;
	countryVertices[112] = country_BY;
	countryVertices[56] = country_BE;
	countryVertices[84] = country_BZ;
	countryVertices[204] = country_BJ;
	countryVertices[60] = country_BM;
	countryVertices[64] = country_BT;
	countryVertices[68] = country_BO;
	countryVertices[535] = country_BQ;
	countryVertices[70] = country_BA;
	countryVertices[72] = country_BW;
	countryVertices[74] = country_BV;
	countryVertices[76] = country_BR;
	countryVertices[86] = country_IO;
	countryVertices[96] = country_BN;
	countryVertices[100] = country_BG;
	countryVertices[854] = country_BF;
	countryVertices[108] = country_BI;
	countryVertices[132] = country_CV;
	countryVertices[116] = country_KH;
	countryVertices[120] = country_CM;
	countryVertices[124] = country_CA;
	countryVertices[136] = country_KY;
	countryVertices[140] = country_CF;
	countryVertices[148] = country_TD;
	countryVertices[152] = country_CL;
	countryVertices[156] = country_CN;
	countryVertices[162] = country_CX;
	countryVertices[166] = country_CC;
	countryVertices[170] = country_CO;
	countryVertices[174] = country_KM;
	countryVertices[178] = country_CG;
	countryVertices[180] = country_CD;
	countryVertices[184] = country_CK;
	countryVertices[188] = country_CR;
	countryVertices[384] = country_CI;
	countryVertices[191] = country_HR;
	countryVertices[192] = country_CU;
	countryVertices[531] = country_CW;
	countryVertices[196] = country_CY;
	countryVertices[203] = country_CZ;
	countryVertices[208] = country_DK;
	countryVertices[262] = country_DJ;
	countryVertices[212] = country_DM;
	countryVertices[214] = country_DO;
	countryVertices[218] = country_EC;
	countryVertices[818] = country_EG;
	countryVertices[222] = country_SV;
	countryVertices[226] = country_GQ;
	countryVertices[232] = country_ER;
	countryVertices[233] = country_EE;
	countryVertices[748] = country_SZ;
	countryVertices[231] = country_ET;
	countryVertices[238] = country_FK;
	countryVertices[234] = country_FO;
	countryVertices[242] = country_FJ;
	countryVertices[246] = country_FI;
	countryVertices[250] = country_FR;
	countryVertices[254] = country_GF;
	countryVertices[258] = country_PF;
	countryVertices[260] = country_TF;
	countryVertices[266] = country_GA;
	countryVertices[270] = country_GM;
	countryVertices[268] = country_GE;
	countryVertices[276] = country_DE;
	countryVertices[288] = country_GH;
	countryVertices[292] = country_GI;
	countryVertices[300] = country_GR;
	countryVertices[304] = country_GL;
	countryVertices[308] = country_GD;
	countryVertices[312] = country_GP;
	countryVertices[316] = country_GU;
	countryVertices[320] = country_GT;
	countryVertices[831] = country_GG;
	countryVertices[324] = country_GN;
	countryVertices[624] = country_GW;
	countryVertices[328] = country_GY;
	countryVertices[332] = country_HT;
	countryVertices[334] = country_HM;
	countryVertices[336] = country_VA;
	countryVertices[340] = country_HN;
	countryVertices[344] = country_HK;
	countryVertices[348] = country_HU;
	countryVertices[352] = country_IS;
	countryVertices[356] = country_IN;
	countryVertices[360] = country_ID;
	countryVertices[364] = country_IR;
	countryVertices[368] = country_IQ;
	countryVertices[372] = country_IE;
	countryVertices[833] = country_IM;
	countryVertices[376] = country_IL;
	countryVertices[380] = country_IT;
	countryVertices[388] = country_JM;
	countryVertices[392] = country_JP;
	countryVertices[832] = country_JE;
	countryVertices[400] = country_JO;
	countryVertices[398] = country_KZ;
	countryVertices[404] = country_KE;
	countryVertices[296] = country_KI;
	countryVertices[408] = country_KP;
	countryVertices[410] = country_KR;
	countryVertices[414] = country_KW;
	countryVertices[417] = country_KG;
	countryVertices[418] = country_LA;
	countryVertices[428] = country_LV;
	countryVertices[422] = country_LB;
	countryVertices[426] = country_LS;
	countryVertices[430] = country_LR;
	countryVertices[434] = country_LY;
	countryVertices[438] = country_LI;
	countryVertices[440] = country_LT;
	countryVertices[442] = country_LU;
	countryVertices[446] = country_MO;
	countryVertices[450] = country_MG;
	countryVertices[454] = country_MW;
	countryVertices[458] = country_MY;
	countryVertices[462] = country_MV;
	countryVertices[466] = country_ML;
	countryVertices[470] = country_MT;
	countryVertices[584] = country_MH;
	countryVertices[474] = country_MQ;
	countryVertices[478] = country_MR;
	countryVertices[480] = country_MU;
	countryVertices[175] = country_YT;
	countryVertices[484] = country_MX;
	countryVertices[583] = country_FM;
	countryVertices[498] = country_MD;
	countryVertices[492] = country_MC;
	countryVertices[496] = country_MN;
	countryVertices[499] = country_ME;
	countryVertices[500] = country_MS;
	countryVertices[504] = country_MA;
	countryVertices[508] = country_MZ;
	countryVertices[104] = country_MM;
	countryVertices[516] = country_NA;
	countryVertices[520] = country_NR;
	countryVertices[524] = country_NP;
	countryVertices[528] = country_NL;
	countryVertices[540] = country_NC;
	countryVertices[554] = country_NZ;
	countryVertices[558] = country_NI;
	countryVertices[562] = country_NE;
	countryVertices[566] = country_NG;
	countryVertices[570] = country_NU;
	countryVertices[574] = country_NF;
	countryVertices[807] = country_MK;
	countryVertices[580] = country_MP;
	countryVertices[578] = country_NO;
	countryVertices[512] = country_OM;
	countryVertices[586] = country_PK;
	countryVertices[585] = country_PW;
	countryVertices[275] = country_PS;
	countryVertices[591] = country_PA;
	countryVertices[598] = country_PG;
	countryVertices[600] = country_PY;
	countryVertices[604] = country_PE;
	countryVertices[608] = country_PH;
	countryVertices[612] = country_PN;
	countryVertices[616] = country_PL;
	countryVertices[620] = country_PT;
	countryVertices[630] = country_PR;
	countryVertices[634] = country_QA;
	countryVertices[638] = country_RE;
	countryVertices[642] = country_RO;
	countryVertices[643] = country_RU;
	countryVertices[646] = country_RW;
	countryVertices[652] = country_BL;
	countryVertices[654] = country_SH;
	countryVertices[659] = country_KN;
	countryVertices[662] = country_LC;
	countryVertices[663] = country_MF;
	countryVertices[666] = country_PM;
	countryVertices[670] = country_VC;
	countryVertices[882] = country_WS;
	countryVertices[674] = country_SM;
	countryVertices[678] = country_ST;
	countryVertices[682] = country_SA;
	countryVertices[686] = country_SN;
	countryVertices[688] = country_RS;
	countryVertices[690] = country_SC;
	countryVertices[694] = country_SL;
	countryVertices[702] = country_SG;
	countryVertices[534] = country_SX;
	countryVertices[703] = country_SK;
	countryVertices[705] = country_SI;
	countryVertices[90] = country_SB;
	countryVertices[706] = country_SO;
	countryVertices[710] = country_ZA;
	countryVertices[239] = country_GS;
	countryVertices[728] = country_SS;
	countryVertices[724] = country_ES;
	countryVertices[144] = country_LK;
	countryVertices[729] = country_SD;
	countryVertices[740] = country_SR;
	countryVertices[744] = country_SJ;
	countryVertices[752] = country_SE;
	countryVertices[756] = country_CH;
	countryVertices[760] = country_SY;
	countryVertices[158] = country_TW;
	countryVertices[762] = country_TJ;
	countryVertices[834] = country_TZ;
	countryVertices[764] = country_TH;
	countryVertices[626] = country_TL;
	countryVertices[768] = country_TG;
	countryVertices[772] = country_TK;
	countryVertices[776] = country_TO;
	countryVertices[780] = country_TT;
	countryVertices[788] = country_TN;
	countryVertices[792] = country_TR;
	countryVertices[795] = country_TM;
	countryVertices[796] = country_TC;
	countryVertices[798] = country_TV;
	countryVertices[800] = country_UG;
	countryVertices[804] = country_UA;
	countryVertices[784] = country_AE;
	countryVertices[826] = country_GB;
	countryVertices[840] = country_US;
	countryVertices[581] = country_UM;
	countryVertices[858] = country_UY;
	countryVertices[860] = country_UZ;
	countryVertices[548] = country_VU;
	countryVertices[862] = country_VE;
	countryVertices[704] = country_VN;
	countryVertices[92] = country_VG;
	countryVertices[850] = country_VI;
	countryVertices[876] = country_WF;
	countryVertices[732] = country_EH;
	countryVertices[887] = country_YE;
	countryVertices[894] = country_ZM;
	countryVertices[716] = country_ZW;

	// Create edges for each land border
	add_edge(country_AD, country_FR);
	add_edge(country_AD, country_ES);
	add_edge(country_AE, country_OM);
	add_edge(country_AE, country_SA);
	add_edge(country_AF, country_CN);
	add_edge(country_AF, country_IR);
	add_edge(country_AF, country_PK);
	add_edge(country_AF, country_TJ);
	add_edge(country_AF, country_TM);
	add_edge(country_AF, country_UZ);
	add_edge(country_AL, country_GR);
	add_edge(country_AL, country_ME);
	add_edge(country_AL, country_MK);
	add_edge(country_AL, country_RS);
	add_edge(country_AM, country_AZ);
	add_edge(country_AM, country_GE);
	add_edge(country_AM, country_IR);
	add_edge(country_AM, country_TR);
	add_edge(country_AO, country_CG);
	add_edge(country_AO, country_CD);
	add_edge(country_AO, country_NA);
	add_edge(country_AO, country_ZM);
	add_edge(country_AR, country_BO);
	add_edge(country_AR, country_BR);
	add_edge(country_AR, country_CL);
	add_edge(country_AR, country_PY);
	add_edge(country_AR, country_UY);
	add_edge(country_AT, country_CZ);
	add_edge(country_AT, country_DE);
	add_edge(country_AT, country_HU);
	add_edge(country_AT, country_IT);
	add_edge(country_AT, country_LI);
	add_edge(country_AT, country_SK);
	add_edge(country_AT, country_SI);
	add_edge(country_AT, country_CH);
	add_edge(country_AZ, country_AM);
	add_edge(country_AZ, country_GE);
	add_edge(country_AZ, country_IR);
	add_edge(country_AZ, country_RU);
	add_edge(country_AZ, country_TR);
	add_edge(country_BA, country_HR);
	add_edge(country_BA, country_ME);
	add_edge(country_BA, country_RS);
	add_edge(country_BD, country_IN);
	add_edge(country_BD, country_MM);
	add_edge(country_BE, country_FR);
	add_edge(country_BE, country_DE);
	add_edge(country_BE, country_LU);
	add_edge(country_BE, country_NL);
	add_edge(country_BF, country_BJ);
	add_edge(country_BF, country_CI);
	add_edge(country_BF, country_GH);
	add_edge(country_BF, country_ML);
	add_edge(country_BF, country_NE);
	add_edge(country_BF, country_TG);
	add_edge(country_BG, country_GR);
	add_edge(country_BG, country_MK);
	add_edge(country_BG, country_RO);
	add_edge(country_BG, country_RS);
	add_edge(country_BG, country_TR);
	add_edge(country_BI, country_CD);
	add_edge(country_BI, country_RW);
	add_edge(country_BI, country_TZ);
	add_edge(country_BJ, country_BF);
	add_edge(country_BJ, country_NE);
	add_edge(country_BJ, country_NG);
	add_edge(country_BJ, country_TG);
	add_edge(country_BN, country_MY);
	add_edge(country_BO, country_AR);
	add_edge(country_BO, country_BR);
	add_edge(country_BO, country_CL);
	add_edge(country_BO, country_PY);
	add_edge(country_BO, country_PE);
	add_edge(country_BR, country_AR);
	add_edge(country_BR, country_BO);
	add_edge(country_BR, country_CO);
	add_edge(country_BR, country_GF);
	add_edge(country_BR, country_GY);
	add_edge(country_BR, country_PY);
	add_edge(country_BR, country_PE);
	add_edge(country_BR, country_SR);
	add_edge(country_BR, country_UY);
	add_edge(country_BR, country_VE);
	add_edge(country_BT, country_CN);
	add_edge(country_BT, country_IN);
	add_edge(country_BW, country_NA);
	add_edge(country_BW, country_ZA);
	add_edge(country_BW, country_ZM);
	add_edge(country_BW, country_ZW);
	add_edge(country_BY, country_LV);
	add_edge(country_BY, country_LT);
	add_edge(country_BY, country_PL);
	add_edge(country_BY, country_RU);
	add_edge(country_BY, country_UA);
	add_edge(country_BZ, country_GT);
	add_edge(country_BZ, country_MX);
	add_edge(country_CA, country_US);
	add_edge(country_CD, country_AO);
	add_edge(country_CD, country_BI);
	add_edge(country_CD, country_CF);
	add_edge(country_CD, country_CG);
	add_edge(country_CD, country_RW);
	add_edge(country_CD, country_SS);
	add_edge(country_CD, country_TZ);
	add_edge(country_CD, country_UG);
	add_edge(country_CD, country_ZM);
	add_edge(country_CF, country_CM);
	add_edge(country_CF, country_TD);
	add_edge(country_CF, country_CG);
	add_edge(country_CF, country_CD);
	add_edge(country_CF, country_SS);
	add_edge(country_CF, country_SD);
	add_edge(country_CG, country_AO);
	add_edge(country_CG, country_CM);
	add_edge(country_CG, country_CF);
	add_edge(country_CG, country_CD);
	add_edge(country_CG, country_GA);
	add_edge(country_CH, country_AT);
	add_edge(country_CH, country_FR);
	add_edge(country_CH, country_DE);
	add_edge(country_CH, country_IT);
	add_edge(country_CH, country_LI);
	add_edge(country_CI, country_BF);
	add_edge(country_CI, country_GH);
	add_edge(country_CI, country_GN);
	add_edge(country_CI, country_LR);
	add_edge(country_CI, country_ML);
	add_edge(country_CL, country_AR);
	add_edge(country_CL, country_BO);
	add_edge(country_CL, country_PE);
	add_edge(country_CM, country_CF);
	add_edge(country_CM, country_TD);
	add_edge(country_CM, country_CG);
	add_edge(country_CM, country_GQ);
	add_edge(country_CM, country_GA);
	add_edge(country_CM, country_NG);
	add_edge(country_CN, country_AF);
	add_edge(country_CN, country_BT);
	add_edge(country_CN, country_HK);
	add_edge(country_CN, country_IN);
	add_edge(country_CN, country_KZ);
	add_edge(country_CN, country_KP);
	add_edge(country_CN, country_KG);
	add_edge(country_CN, country_LA);
	add_edge(country_CN, country_MO);
	add_edge(country_CN, country_MN);
	add_edge(country_CN, country_MM);
	add_edge(country_CN, country_NP);
	add_edge(country_CN, country_PK);
	add_edge(country_CN, country_RU);
	add_edge(country_CN, country_TJ);
	add_edge(country_CN, country_VN);
	add_edge(country_CO, country_BR);
	add_edge(country_CO, country_EC);
	add_edge(country_CO, country_PA);
	add_edge(country_CO, country_PE);
	add_edge(country_CO, country_VE);
	add_edge(country_CR, country_NI);
	add_edge(country_CR, country_PA);
	add_edge(country_CZ, country_AT);
	add_edge(country_CZ, country_DE);
	add_edge(country_CZ, country_PL);
	add_edge(country_CZ, country_SK);
	add_edge(country_DE, country_AT);
	add_edge(country_DE, country_BE);
	add_edge(country_DE, country_CZ);
	add_edge(country_DE, country_DK);
	add_edge(country_DE, country_FR);
	add_edge(country_DE, country_LU);
	add_edge(country_DE, country_NL);
	add_edge(country_DE, country_PL);
	add_edge(country_DE, country_CH);
	add_edge(country_DJ, country_ER);
	add_edge(country_DJ, country_ET);
	add_edge(country_DJ, country_SO);
	add_edge(country_DK, country_DE);
	add_edge(country_DO, country_HT);
	add_edge(country_DZ, country_LY);
	add_edge(country_DZ, country_ML);
	add_edge(country_DZ, country_MR);
	add_edge(country_DZ, country_MA);
	add_edge(country_DZ, country_NE);
	add_edge(country_DZ, country_TN);
	add_edge(country_DZ, country_EH);
	add_edge(country_EC, country_CO);
	add_edge(country_EC, country_PE);
	add_edge(country_EE, country_LV);
	add_edge(country_EE, country_RU);
	add_edge(country_EG, country_IL);
	add_edge(country_EG, country_LY);
	add_edge(country_EG, country_PS);
	add_edge(country_EG, country_SD);
	add_edge(country_EH, country_DZ);
	add_edge(country_EH, country_MR);
	add_edge(country_EH, country_MA);
	add_edge(country_ER, country_DJ);
	add_edge(country_ER, country_ET);
	add_edge(country_ER, country_SD);
	add_edge(country_ES, country_AD);
	add_edge(country_ES, country_FR);
	add_edge(country_ES, country_GI);
	add_edge(country_ES, country_MA);
	add_edge(country_ES, country_PT);
	add_edge(country_ET, country_DJ);
	add_edge(country_ET, country_ER);
	add_edge(country_ET, country_KE);
	add_edge(country_ET, country_SO);
	add_edge(country_ET, country_SS);
	add_edge(country_ET, country_SD);
	add_edge(country_FI, country_NO);
	add_edge(country_FI, country_RU);
	add_edge(country_FI, country_SE);
	add_edge(country_FR, country_AD);
	add_edge(country_FR, country_BE);
	add_edge(country_FR, country_DE);
	add_edge(country_FR, country_IT);
	add_edge(country_FR, country_LU);
	add_edge(country_FR, country_MC);
	add_edge(country_FR, country_ES);
	add_edge(country_FR, country_CH);
	add_edge(country_GA, country_CM);
	add_edge(country_GA, country_CG);
	add_edge(country_GA, country_GQ);
	add_edge(country_GB, country_IE);
	add_edge(country_GE, country_AM);
	add_edge(country_GE, country_AZ);
	add_edge(country_GE, country_RU);
	add_edge(country_GE, country_TR);
	add_edge(country_GF, country_BR);
	add_edge(country_GF, country_SR);
	add_edge(country_GH, country_BF);
	add_edge(country_GH, country_CI);
	add_edge(country_GH, country_TG);
	add_edge(country_GI, country_ES);
	add_edge(country_GM, country_SN);
	add_edge(country_GN, country_CI);
	add_edge(country_GN, country_GW);
	add_edge(country_GN, country_LR);
	add_edge(country_GN, country_ML);
	add_edge(country_GN, country_SN);
	add_edge(country_GN, country_SL);
	add_edge(country_GQ, country_CM);
	add_edge(country_GQ, country_GA);
	add_edge(country_GR, country_AL);
	add_edge(country_GR, country_BG);
	add_edge(country_GR, country_MK);
	add_edge(country_GR, country_TR);
	add_edge(country_GT, country_BZ);
	add_edge(country_GT, country_SV);
	add_edge(country_GT, country_HN);
	add_edge(country_GT, country_MX);
	add_edge(country_GW, country_GN);
	add_edge(country_GW, country_SN);
	add_edge(country_GY, country_BR);
	add_edge(country_GY, country_SR);
	add_edge(country_GY, country_VE);
	add_edge(country_HK, country_CN);
	add_edge(country_HN, country_SV);
	add_edge(country_HN, country_GT);
	add_edge(country_HN, country_NI);
	add_edge(country_HR, country_BA);
	add_edge(country_HR, country_HU);
	add_edge(country_HR, country_ME);
	add_edge(country_HR, country_RS);
	add_edge(country_HR, country_SI);
	add_edge(country_HT, country_DO);
	add_edge(country_HU, country_AT);
	add_edge(country_HU, country_HR);
	add_edge(country_HU, country_RO);
	add_edge(country_HU, country_RS);
	add_edge(country_HU, country_SK);
	add_edge(country_HU, country_SI);
	add_edge(country_HU, country_UA);
	add_edge(country_ID, country_MY);
	add_edge(country_ID, country_PG);
	add_edge(country_ID, country_TL);
	add_edge(country_IE, country_GB);
	add_edge(country_IL, country_EG);
	add_edge(country_IL, country_JO);
	add_edge(country_IL, country_LB);
	add_edge(country_IL, country_PS);
	add_edge(country_IL, country_SY);
	add_edge(country_IN, country_BD);
	add_edge(country_IN, country_BT);
	add_edge(country_IN, country_CN);
	add_edge(country_IN, country_MM);
	add_edge(country_IN, country_NP);
	add_edge(country_IN, country_PK);
	add_edge(country_IQ, country_IR);
	add_edge(country_IQ, country_JO);
	add_edge(country_IQ, country_KW);
	add_edge(country_IQ, country_SA);
	add_edge(country_IQ, country_SY);
	add_edge(country_IQ, country_TR);
	add_edge(country_IR, country_AF);
	add_edge(country_IR, country_AM);
	add_edge(country_IR, country_AZ);
	add_edge(country_IR, country_IQ);
	add_edge(country_IR, country_PK);
	add_edge(country_IR, country_TR);
	add_edge(country_IR, country_TM);
	add_edge(country_IT, country_AT);
	add_edge(country_IT, country_FR);
	add_edge(country_IT, country_SM);
	add_edge(country_IT, country_SI);
	add_edge(country_IT, country_CH);
	add_edge(country_IT, country_VA);
	add_edge(country_JO, country_IQ);
	add_edge(country_JO, country_IL);
	add_edge(country_JO, country_PS);
	add_edge(country_JO, country_SA);
	add_edge(country_JO, country_SY);
	add_edge(country_KE, country_ET);
	add_edge(country_KE, country_SO);
	add_edge(country_KE, country_SS);
	add_edge(country_KE, country_TZ);
	add_edge(country_KE, country_UG);
	add_edge(country_KG, country_CN);
	add_edge(country_KG, country_KZ);
	add_edge(country_KG, country_TJ);
	add_edge(country_KG, country_UZ);
	add_edge(country_KH, country_LA);
	add_edge(country_KH, country_TH);
	add_edge(country_KH, country_VN);
	add_edge(country_KP, country_CN);
	add_edge(country_KP, country_KR);
	add_edge(country_KP, country_RU);
	add_edge(country_KR, country_KP);
	add_edge(country_KW, country_IQ);
	add_edge(country_KW, country_SA);
	add_edge(country_KZ, country_CN);
	add_edge(country_KZ, country_KG);
	add_edge(country_KZ, country_RU);
	add_edge(country_KZ, country_TM);
	add_edge(country_KZ, country_UZ);
	add_edge(country_LA, country_CN);
	add_edge(country_LA, country_KH);
	add_edge(country_LA, country_MM);
	add_edge(country_LA, country_TH);
	add_edge(country_LA, country_VN);
	add_edge(country_LB, country_IL);
	add_edge(country_LB, country_SY);
	add_edge(country_LI, country_AT);
	add_edge(country_LI, country_CH);
	add_edge(country_LR, country_CI);
	add_edge(country_LR, country_GN);
	add_edge(country_LR, country_SL);
	add_edge(country_LS, country_ZA);
	add_edge(country_LT, country_BY);
	add_edge(country_LT, country_LV);
	add_edge(country_LT, country_PL);
	add_edge(country_LT, country_RU);
	add_edge(country_LU, country_BE);
	add_edge(country_LU, country_DE);
	add_edge(country_LU, country_FR);
	add_edge(country_LV, country_BY);
	add_edge(country_LV, country_EE);
	add_edge(country_LV, country_LT);
	add_edge(country_LV, country_RU);
	add_edge(country_LY, country_DZ);
	add_edge(country_LY, country_TD);
	add_edge(country_LY, country_EG);
	add_edge(country_LY, country_NE);
	add_edge(country_LY, country_SD);
	add_edge(country_LY, country_TN);
	add_edge(country_MA, country_DZ);
	add_edge(country_MA, country_ES);
	add_edge(country_MA, country_EH);
	add_edge(country_MC, country_FR);
	add_edge(country_MD, country_RO);
	add_edge(country_MD, country_UA);
	add_edge(country_ME, country_AL);
	add_edge(country_ME, country_BA);
	add_edge(country_ME, country_HR);
	add_edge(country_ME, country_RS);
	add_edge(country_MF, country_SX);
	add_edge(country_MK, country_AL);
	add_edge(country_MK, country_BG);
	add_edge(country_MK, country_GR);
	add_edge(country_MK, country_RS);
	add_edge(country_ML, country_DZ);
	add_edge(country_ML, country_BF);
	add_edge(country_ML, country_CI);
	add_edge(country_ML, country_GN);
	add_edge(country_ML, country_MR);
	add_edge(country_ML, country_NE);
	add_edge(country_ML, country_SN);
	add_edge(country_MM, country_BD);
	add_edge(country_MM, country_CN);
	add_edge(country_MM, country_IN);
	add_edge(country_MM, country_LA);
	add_edge(country_MM, country_TH);
	add_edge(country_MN, country_CN);
	add_edge(country_MN, country_RU);
	add_edge(country_MO, country_CN);
	add_edge(country_MR, country_DZ);
	add_edge(country_MR, country_ML);
	add_edge(country_MR, country_SN);
	add_edge(country_MR, country_EH);
	add_edge(country_MW, country_MZ);
	add_edge(country_MW, country_TZ);
	add_edge(country_MW, country_ZM);
	add_edge(country_MX, country_BZ);
	add_edge(country_MX, country_GT);
	add_edge(country_MX, country_US);
	add_edge(country_MY, country_BN);
	add_edge(country_MY, country_ID);
	add_edge(country_MY, country_TH);
	add_edge(country_MZ, country_MW);
	add_edge(country_MZ, country_SZ);
	add_edge(country_MZ, country_ZA);
	add_edge(country_MZ, country_TZ);
	add_edge(country_MZ, country_ZM);
	add_edge(country_MZ, country_ZW);
	add_edge(country_NA, country_AO);
	add_edge(country_NA, country_BW);
	add_edge(country_NA, country_ZA);
	add_edge(country_NA, country_ZM);
	add_edge(country_NE, country_DZ);
	add_edge(country_NE, country_BJ);
	add_edge(country_NE, country_BF);
	add_edge(country_NE, country_TD);
	add_edge(country_NE, country_LY);
	add_edge(country_NE, country_ML);
	add_edge(country_NE, country_NG);
	add_edge(country_NG, country_BJ);
	add_edge(country_NG, country_CM);
	add_edge(country_NG, country_TD);
	add_edge(country_NG, country_NE);
	add_edge(country_NI, country_CR);
	add_edge(country_NI, country_HN);
	add_edge(country_NL, country_BE);
	add_edge(country_NL, country_DE);
	add_edge(country_NO, country_FI);
	add_edge(country_NO, country_RU);
	add_edge(country_NO, country_SE);
	add_edge(country_NP, country_CN);
	add_edge(country_NP, country_IN);
	add_edge(country_OM, country_AE);
	add_edge(country_OM, country_SA);
	add_edge(country_OM, country_YE);
	add_edge(country_PA, country_CO);
	add_edge(country_PA, country_CR);
	add_edge(country_PE, country_BO);
	add_edge(country_PE, country_BR);
	add_edge(country_PE, country_CL);
	add_edge(country_PE, country_CO);
	add_edge(country_PE, country_EC);
	add_edge(country_PG, country_ID);
	add_edge(country_PK, country_AF);
	add_edge(country_PK, country_CN);
	add_edge(country_PK, country_IN);
	add_edge(country_PK, country_IR);
	add_edge(country_PL, country_BY);
	add_edge(country_PL, country_CZ);
	add_edge(country_PL, country_DE);
	add_edge(country_PL, country_LT);
	add_edge(country_PL, country_RU);
	add_edge(country_PL, country_SK);
	add_edge(country_PL, country_UA);
	add_edge(country_PS, country_EG);
	add_edge(country_PS, country_IL);
	add_edge(country_PS, country_JO);
	add_edge(country_PT, country_ES);
	add_edge(country_PY, country_AR);
	add_edge(country_PY, country_BO);
	add_edge(country_PY, country_BR);
	add_edge(country_QA, country_SA);
	add_edge(country_RO, country_BG);
	add_edge(country_RO, country_HU);
	add_edge(country_RO, country_MD);
	add_edge(country_RO, country_RS);
	add_edge(country_RO, country_UA);
	add_edge(country_RS, country_AL);
	add_edge(country_RS, country_BA);
	add_edge(country_RS, country_BG);
	add_edge(country_RS, country_HR);
	add_edge(country_RS, country_HU);
	add_edge(country_RS, country_ME);
	add_edge(country_RS, country_MK);
	add_edge(country_RS, country_RO);
	add_edge(country_RU, country_AZ);
	add_edge(country_RU, country_BY);
	add_edge(country_RU, country_CN);
	add_edge(country_RU, country_EE);
	add_edge(country_RU, country_FI);
	add_edge(country_RU, country_GE);
	add_edge(country_RU, country_KZ);
	add_edge(country_RU, country_KP);
	add_edge(country_RU, country_LV);
	add_edge(country_RU, country_LT);
	add_edge(country_RU, country_MN);
	add_edge(country_RU, country_NO);
	add_edge(country_RU, country_PL);
	add_edge(country_RU, country_UA);
	add_edge(country_RW, country_BI);
	add_edge(country_RW, country_CD);
	add_edge(country_RW, country_TZ);
	add_edge(country_RW, country_UG);
	add_edge(country_SA, country_IQ);
	add_edge(country_SA, country_JO);
	add_edge(country_SA, country_KW);
	add_edge(country_SA, country_OM);
	add_edge(country_SA, country_QA);
	add_edge(country_SA, country_AE);
	add_edge(country_SA, country_YE);
	add_edge(country_SD, country_CF);
	add_edge(country_SD, country_TD);
	add_edge(country_SD, country_EG);
	add_edge(country_SD, country_ET);
	add_edge(country_SD, country_ER);
	add_edge(country_SD, country_LY);
	add_edge(country_SD, country_SS);
	add_edge(country_SE, country_FI);
	add_edge(country_SE, country_NO);
	add_edge(country_SI, country_AT);
	add_edge(country_SI, country_HR);
	add_edge(country_SI, country_HU);
	add_edge(country_SI, country_IT);
	add_edge(country_SK, country_AT);
	add_edge(country_SK, country_CZ);
	add_edge(country_SK, country_HU);
	add_edge(country_SK, country_PL);
	add_edge(country_SK, country_UA);
	add_edge(country_SL, country_GN);
	add_edge(country_SL, country_LR);
	add_edge(country_SM, country_IT);
	add_edge(country_SN, country_GM);
	add_edge(country_SN, country_GN);
	add_edge(country_SN, country_GW);
	add_edge(country_SN, country_ML);
	add_edge(country_SN, country_MR);
	add_edge(country_SO, country_DJ);
	add_edge(country_SO, country_ET);
	add_edge(country_SO, country_KE);
	add_edge(country_SR, country_BR);
	add_edge(country_SR, country_GF);
	add_edge(country_SR, country_GY);
	add_edge(country_SS, country_CF);
	add_edge(country_SS, country_CD);
	add_edge(country_SS, country_ET);
	add_edge(country_SS, country_KE);
	add_edge(country_SS, country_SD);
	add_edge(country_SS, country_UG);
	add_edge(country_SV, country_GT);
	add_edge(country_SV, country_HN);
	add_edge(country_SX, country_MF);
	add_edge(country_SY, country_IQ);
	add_edge(country_SY, country_IL);
	add_edge(country_SY, country_JO);
	add_edge(country_SY, country_LB);
	add_edge(country_SY, country_TR);
	add_edge(country_SZ, country_MZ);
	add_edge(country_SZ, country_ZA);
	add_edge(country_TD, country_CM);
	add_edge(country_TD, country_CF);
	add_edge(country_TD, country_LY);
	add_edge(country_TD, country_NE);
	add_edge(country_TD, country_NG);
	add_edge(country_TD, country_SD);
	add_edge(country_TG, country_BJ);
	add_edge(country_TG, country_BF);
	add_edge(country_TG, country_GH);
	add_edge(country_TH, country_KH);
	add_edge(country_TH, country_LA);
	add_edge(country_TH, country_MY);
	add_edge(country_TH, country_MM);
	add_edge(country_TJ, country_AF);
	add_edge(country_TJ, country_CN);
	add_edge(country_TJ, country_KG);
	add_edge(country_TJ, country_UZ);
	add_edge(country_TL, country_ID);
	add_edge(country_TM, country_AF);
	add_edge(country_TM, country_IR);
	add_edge(country_TM, country_KZ);
	add_edge(country_TM, country_UZ);
	add_edge(country_TN, country_DZ);
	add_edge(country_TN, country_LY);
	add_edge(country_TR, country_AM);
	add_edge(country_TR, country_AZ);
	add_edge(country_TR, country_BG);
	add_edge(country_TR, country_GE);
	add_edge(country_TR, country_GR);
	add_edge(country_TR, country_IR);
	add_edge(country_TR, country_IQ);
	add_edge(country_TR, country_SY);
	add_edge(country_TZ, country_BI);
	add_edge(country_TZ, country_CD);
	add_edge(country_TZ, country_KE);
	add_edge(country_TZ, country_MW);
	add_edge(country_TZ, country_MZ);
	add_edge(country_TZ, country_RW);
	add_edge(country_TZ, country_UG);
	add_edge(country_TZ, country_ZM);
	add_edge(country_UA, country_BY);
	add_edge(country_UA, country_HU);
	add_edge(country_UA, country_MD);
	add_edge(country_UA, country_PL);
	add_edge(country_UA, country_RO);
	add_edge(country_UA, country_RU);
	add_edge(country_UA, country_SK);
	add_edge(country_UG, country_CD);
	add_edge(country_UG, country_KE);
	add_edge(country_UG, country_RW);
	add_edge(country_UG, country_SS);
	add_edge(country_UG, country_TZ);
	add_edge(country_US, country_CA);
	add_edge(country_US, country_MX);
	add_edge(country_UY, country_AR);
	add_edge(country_UY, country_BR);
	add_edge(country_UZ, country_AF);
	add_edge(country_UZ, country_KZ);
	add_edge(country_UZ, country_KG);
	add_edge(country_UZ, country_TJ);
	add_edge(country_UZ, country_TM);
	add_edge(country_VA, country_IT);
	add_edge(country_VE, country_BR);
	add_edge(country_VE, country_CO);
	add_edge(country_VE, country_GY);
	add_edge(country_VN, country_KH);
	add_edge(country_VN, country_CN);
	add_edge(country_VN, country_LA);
	add_edge(country_YE, country_OM);
	add_edge(country_YE, country_SA);
	add_edge(country_ZA, country_BW);
	add_edge(country_ZA, country_LS);
	add_edge(country_ZA, country_MZ);
	add_edge(country_ZA, country_NA);
	add_edge(country_ZA, country_SZ);
	add_edge(country_ZA, country_ZW);
	add_edge(country_ZM, country_AO);
	add_edge(country_ZM, country_BW);
	add_edge(country_ZM, country_CD);
	add_edge(country_ZM, country_MW);
	add_edge(country_ZM, country_MZ);
	add_edge(country_ZM, country_NA);
	add_edge(country_ZM, country_TZ);
	add_edge(country_ZM, country_ZW);
	add_edge(country_ZW, country_BW);
	add_edge(country_ZW, country_MZ);
	add_edge(country_ZW, country_ZA);
	add_edge(country_ZW, country_ZM);

	// Test: Path from France to China
	// dictionary_get_value(dictionary , searchkey)
	struct Path * test_path = find_path(country_KR, country_ZA);
	
	for (int i = 0; i < test_path->length; i++)
		printf("%s\n", dictionary_get_value(alpha2_to_name, test_path->vertices[i]));
	path_print(test_path);

	return 0;	
}