/*
 * January 2nd, 2024
 *
 * world.c
 *
 * Graph of all countries in the world that have one or more
 * land borders with another country.
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "../include/hash_table.h"
#include "../include/graph.h"

#define BUFFERSIZE 127

#define ERASENEWLINE(buffer) buffer[strcspn(buffer, "\n")] = '\0'

struct Vertex * select_country(struct hash_table * name_to_alpha2,
	struct hash_table * alpha2_to_numeric,
	struct Vertex ** countryVertices)
{
	printf("Enter the NAME of a country:\n");
	
	// Allocate buffer
	char * linebuf = calloc(BUFFERSIZE, sizeof(char));
	
	// Get user input
	fgets(linebuf, BUFFERSIZE * sizeof(char), stdin);
	
	// fgets() is capturing the newline, set it to a null byte
	ERASENEWLINE(linebuf);
	
	// Get the alpha2 code of the name
	char * alpha2 = dictionary_get_value(name_to_alpha2, linebuf);
	
	// Get the country code number of the alpha2
	char * s_number = dictionary_get_value(alpha2_to_numeric, alpha2);
	
	// Represent that number as a numeric type
	int number = atoi(s_number);
	
	// fetch that vertex from the array
	struct Vertex * selected_country = countryVertices[number];
	free(linebuf);

	// Flush the buffer so no input is carried over.
	fflush(stdin);
	return selected_country;
}

struct Path * user_enter_path(struct hash_table * name_to_alpha2,
	struct hash_table * alpha2_to_numeric,
	struct Vertex ** countryVertices)
{
	char * linebuf = calloc(BUFFERSIZE, sizeof(char));

	struct Path * user_path = construct_path();

	do 
	{
		// Give prompt
		printf("Enter any key to continue or \"done\" to exit:\n");

		// Get input
		fgets(linebuf, BUFFERSIZE * sizeof(char), stdin);

		// fgets() is capturing the newline, set it to a null byte
		ERASENEWLINE(linebuf);

		// Check input
		if (strcmp(linebuf, "done") == 0)
			break;

		// Select a country
		struct Vertex * next_country = select_country(name_to_alpha2,
			alpha2_to_numeric, countryVertices);

		// Add it to the path
		path_insert(user_path, next_country->s_data);
	} while (strcmp(linebuf, "done") != 0);

	path_print(user_path);
	return user_path;
}

struct Vertex * random_country(struct Vertex **countryVertices)
{
	struct Vertex * vert = NULL;

	while (vert == NULL)
	{
		vert = countryVertices[rand() % 896];
	}

	printf("Settled on %s.\n", vert->s_data);

	return vert;
}

int main(void)
{
	// Set up ISO3 -> country name dictionary
	struct hash_table * alpha2_to_name = dictionary_create(500);
	struct hash_table * name_to_alpha2 = dictionary_create(500);
	struct Vertex * countryVertices[895];
	memset(countryVertices, 0, sizeof(struct Vertex *) * 895);
	struct hash_table *alpha2_to_numeric = dictionary_create(500);

	// TODO: all these strdups are ending up as memory leaks
	dictionary_insert(alpha2_to_name, strdup("AF"), strdup("Afghanistan"));
	dictionary_insert(alpha2_to_name, strdup("AL"), strdup("Albania"));
	dictionary_insert(alpha2_to_name, strdup("DZ"), strdup("Algeria"));
	dictionary_insert(alpha2_to_name, strdup("AD"), strdup("Andorra"));
	dictionary_insert(alpha2_to_name, strdup("AO"), strdup("Angola"));
	dictionary_insert(alpha2_to_name, strdup("AR"), strdup("Argentina"));
	dictionary_insert(alpha2_to_name, strdup("AM"), strdup("Armenia"));
	dictionary_insert(alpha2_to_name, strdup("AT"), strdup("Austria"));
	dictionary_insert(alpha2_to_name, strdup("AZ"), strdup("Azerbaijan"));
	dictionary_insert(alpha2_to_name, strdup("BD"), strdup("Bangladesh"));
	dictionary_insert(alpha2_to_name, strdup("BY"), strdup("Belarus"));
	dictionary_insert(alpha2_to_name, strdup("BE"), strdup("Belgium"));
	dictionary_insert(alpha2_to_name, strdup("BZ"), strdup("Belize"));
	dictionary_insert(alpha2_to_name, strdup("BJ"), strdup("Benin"));
	dictionary_insert(alpha2_to_name, strdup("BT"), strdup("Bhutan"));
	dictionary_insert(alpha2_to_name, strdup("BO"), strdup("Bolivia (Plurinational State of)"));
	dictionary_insert(alpha2_to_name, strdup("BQ"), strdup("Bonaire, Sint Eustatius and Saba"));
	dictionary_insert(alpha2_to_name, strdup("BA"), strdup("Bosnia and Herzegovina"));
	dictionary_insert(alpha2_to_name, strdup("BW"), strdup("Botswana"));
	dictionary_insert(alpha2_to_name, strdup("BR"), strdup("Brazil"));
	dictionary_insert(alpha2_to_name, strdup("BN"), strdup("Brunei Darussalam"));
	dictionary_insert(alpha2_to_name, strdup("BG"), strdup("Bulgaria"));
	dictionary_insert(alpha2_to_name, strdup("BF"), strdup("Burkina Faso"));
	dictionary_insert(alpha2_to_name, strdup("BI"), strdup("Burundi"));
	dictionary_insert(alpha2_to_name, strdup("KH"), strdup("Cambodia"));
	dictionary_insert(alpha2_to_name, strdup("CM"), strdup("Cameroon"));
	dictionary_insert(alpha2_to_name, strdup("CA"), strdup("Canada"));
	dictionary_insert(alpha2_to_name, strdup("CF"), strdup("Central African Republic"));
	dictionary_insert(alpha2_to_name, strdup("TD"), strdup("Chad"));
	dictionary_insert(alpha2_to_name, strdup("CL"), strdup("Chile"));
	dictionary_insert(alpha2_to_name, strdup("CN"), strdup("China"));
	dictionary_insert(alpha2_to_name, strdup("CO"), strdup("Colombia"));
	dictionary_insert(alpha2_to_name, strdup("CG"), strdup("Congo"));
	dictionary_insert(alpha2_to_name, strdup("CD"), strdup("Congo, Democratic Republic of the"));
	dictionary_insert(alpha2_to_name, strdup("CR"), strdup("Costa Rica"));
	dictionary_insert(alpha2_to_name, strdup("CI"), strdup("Côte d'Ivoire"));
	dictionary_insert(alpha2_to_name, strdup("HR"), strdup("Croatia"));
	dictionary_insert(alpha2_to_name, strdup("CZ"), strdup("Czechia"));
	dictionary_insert(alpha2_to_name, strdup("DK"), strdup("Denmark"));
	dictionary_insert(alpha2_to_name, strdup("DJ"), strdup("Djibouti"));
	dictionary_insert(alpha2_to_name, strdup("DO"), strdup("Dominican Republic"));
	dictionary_insert(alpha2_to_name, strdup("EC"), strdup("Ecuador"));
	dictionary_insert(alpha2_to_name, strdup("EG"), strdup("Egypt"));
	dictionary_insert(alpha2_to_name, strdup("SV"), strdup("El Salvador"));
	dictionary_insert(alpha2_to_name, strdup("GQ"), strdup("Equatorial Guinea"));
	dictionary_insert(alpha2_to_name, strdup("ER"), strdup("Eritrea"));
	dictionary_insert(alpha2_to_name, strdup("EE"), strdup("Estonia"));
	dictionary_insert(alpha2_to_name, strdup("SZ"), strdup("Eswatini"));
	dictionary_insert(alpha2_to_name, strdup("ET"), strdup("Ethiopia"));
	dictionary_insert(alpha2_to_name, strdup("FI"), strdup("Finland"));
	dictionary_insert(alpha2_to_name, strdup("FR"), strdup("France"));
	dictionary_insert(alpha2_to_name, strdup("GF"), strdup("French Guiana"));
	dictionary_insert(alpha2_to_name, strdup("GA"), strdup("Gabon"));
	dictionary_insert(alpha2_to_name, strdup("GM"), strdup("Gambia"));
	dictionary_insert(alpha2_to_name, strdup("GE"), strdup("Georgia"));
	dictionary_insert(alpha2_to_name, strdup("DE"), strdup("Germany"));
	dictionary_insert(alpha2_to_name, strdup("GH"), strdup("Ghana"));
	dictionary_insert(alpha2_to_name, strdup("GI"), strdup("Gibraltar"));
	dictionary_insert(alpha2_to_name, strdup("GR"), strdup("Greece"));
	dictionary_insert(alpha2_to_name, strdup("GT"), strdup("Guatemala"));
	dictionary_insert(alpha2_to_name, strdup("GN"), strdup("Guinea"));
	dictionary_insert(alpha2_to_name, strdup("GW"), strdup("Guinea-Bissau"));
	dictionary_insert(alpha2_to_name, strdup("GY"), strdup("Guyana"));
	dictionary_insert(alpha2_to_name, strdup("HT"), strdup("Haiti"));
	dictionary_insert(alpha2_to_name, strdup("VA"), strdup("Holy See"));
	dictionary_insert(alpha2_to_name, strdup("HN"), strdup("Honduras"));
	dictionary_insert(alpha2_to_name, strdup("HK"), strdup("Hong Kong"));
	dictionary_insert(alpha2_to_name, strdup("HU"), strdup("Hungary"));
	dictionary_insert(alpha2_to_name, strdup("IN"), strdup("India"));
	dictionary_insert(alpha2_to_name, strdup("ID"), strdup("Indonesia"));
	dictionary_insert(alpha2_to_name, strdup("IR"), strdup("Iran (Islamic Republic of)"));
	dictionary_insert(alpha2_to_name, strdup("IQ"), strdup("Iraq"));
	dictionary_insert(alpha2_to_name, strdup("IE"), strdup("Ireland"));
	dictionary_insert(alpha2_to_name, strdup("IL"), strdup("Israel"));
	dictionary_insert(alpha2_to_name, strdup("IT"), strdup("Italy"));
	dictionary_insert(alpha2_to_name, strdup("JO"), strdup("Jordan"));
	dictionary_insert(alpha2_to_name, strdup("KZ"), strdup("Kazakhstan"));
	dictionary_insert(alpha2_to_name, strdup("KE"), strdup("Kenya"));
	dictionary_insert(alpha2_to_name, strdup("KP"), strdup("Korea (Democratic People's Republic of)"));
	dictionary_insert(alpha2_to_name, strdup("KR"), strdup("Korea, Republic of"));
	dictionary_insert(alpha2_to_name, strdup("KW"), strdup("Kuwait"));
	dictionary_insert(alpha2_to_name, strdup("KG"), strdup("Kyrgyzstan"));
	dictionary_insert(alpha2_to_name, strdup("LA"), strdup("Lao People's Democratic Republic"));
	dictionary_insert(alpha2_to_name, strdup("LV"), strdup("Latvia"));
	dictionary_insert(alpha2_to_name, strdup("LB"), strdup("Lebanon"));
	dictionary_insert(alpha2_to_name, strdup("LS"), strdup("Lesotho"));
	dictionary_insert(alpha2_to_name, strdup("LR"), strdup("Liberia"));
	dictionary_insert(alpha2_to_name, strdup("LY"), strdup("Libya"));
	dictionary_insert(alpha2_to_name, strdup("LI"), strdup("Liechtenstein"));
	dictionary_insert(alpha2_to_name, strdup("LT"), strdup("Lithuania"));
	dictionary_insert(alpha2_to_name, strdup("LU"), strdup("Luxembourg"));
	dictionary_insert(alpha2_to_name, strdup("MO"), strdup("Macao"));
	dictionary_insert(alpha2_to_name, strdup("MW"), strdup("Malawi"));
	dictionary_insert(alpha2_to_name, strdup("MY"), strdup("Malaysia"));
	dictionary_insert(alpha2_to_name, strdup("ML"), strdup("Mali"));
	dictionary_insert(alpha2_to_name, strdup("MR"), strdup("Mauritania"));
	dictionary_insert(alpha2_to_name, strdup("MX"), strdup("Mexico"));
	dictionary_insert(alpha2_to_name, strdup("MD"), strdup("Moldova, Republic of"));
	dictionary_insert(alpha2_to_name, strdup("MC"), strdup("Monaco"));
	dictionary_insert(alpha2_to_name, strdup("MN"), strdup("Mongolia"));
	dictionary_insert(alpha2_to_name, strdup("ME"), strdup("Montenegro"));
	dictionary_insert(alpha2_to_name, strdup("MA"), strdup("Morocco"));
	dictionary_insert(alpha2_to_name, strdup("MZ"), strdup("Mozambique"));
	dictionary_insert(alpha2_to_name, strdup("MM"), strdup("Myanmar"));
	dictionary_insert(alpha2_to_name, strdup("NA"), strdup("Namibia"));
	dictionary_insert(alpha2_to_name, strdup("NP"), strdup("Nepal"));
	dictionary_insert(alpha2_to_name, strdup("NL"), strdup("Netherlands"));
	dictionary_insert(alpha2_to_name, strdup("NI"), strdup("Nicaragua"));
	dictionary_insert(alpha2_to_name, strdup("NE"), strdup("Niger"));
	dictionary_insert(alpha2_to_name, strdup("NG"), strdup("Nigeria"));
	dictionary_insert(alpha2_to_name, strdup("MK"), strdup("North Macedonia"));
	dictionary_insert(alpha2_to_name, strdup("NO"), strdup("Norway"));
	dictionary_insert(alpha2_to_name, strdup("OM"), strdup("Oman"));
	dictionary_insert(alpha2_to_name, strdup("PK"), strdup("Pakistan"));
	dictionary_insert(alpha2_to_name, strdup("PS"), strdup("Palestine, State of"));
	dictionary_insert(alpha2_to_name, strdup("PA"), strdup("Panama"));
	dictionary_insert(alpha2_to_name, strdup("PG"), strdup("Papua New Guinea"));
	dictionary_insert(alpha2_to_name, strdup("PY"), strdup("Paraguay"));
	dictionary_insert(alpha2_to_name, strdup("PE"), strdup("Peru"));
	dictionary_insert(alpha2_to_name, strdup("PL"), strdup("Poland"));
	dictionary_insert(alpha2_to_name, strdup("PT"), strdup("Portugal"));
	dictionary_insert(alpha2_to_name, strdup("QA"), strdup("Qatar"));
	dictionary_insert(alpha2_to_name, strdup("RO"), strdup("Romania"));
	dictionary_insert(alpha2_to_name, strdup("RU"), strdup("Russian Federation"));
	dictionary_insert(alpha2_to_name, strdup("RW"), strdup("Rwanda"));
	dictionary_insert(alpha2_to_name, strdup("MF"), strdup("Saint Martin (French part)"));
	dictionary_insert(alpha2_to_name, strdup("SM"), strdup("San Marino"));
	dictionary_insert(alpha2_to_name, strdup("SA"), strdup("Saudi Arabia"));
	dictionary_insert(alpha2_to_name, strdup("SN"), strdup("Senegal"));
	dictionary_insert(alpha2_to_name, strdup("RS"), strdup("Serbia"));
	dictionary_insert(alpha2_to_name, strdup("SL"), strdup("Sierra Leone"));
	dictionary_insert(alpha2_to_name, strdup("SX"), strdup("Sint Maarten (Dutch part)"));
	dictionary_insert(alpha2_to_name, strdup("SK"), strdup("Slovakia"));
	dictionary_insert(alpha2_to_name, strdup("SI"), strdup("Slovenia"));
	dictionary_insert(alpha2_to_name, strdup("SO"), strdup("Somalia"));
	dictionary_insert(alpha2_to_name, strdup("ZA"), strdup("South Africa"));
	dictionary_insert(alpha2_to_name, strdup("SS"), strdup("South Sudan"));
	dictionary_insert(alpha2_to_name, strdup("ES"), strdup("Spain"));
	dictionary_insert(alpha2_to_name, strdup("SD"), strdup("Sudan"));
	dictionary_insert(alpha2_to_name, strdup("SR"), strdup("Suriname"));
	dictionary_insert(alpha2_to_name, strdup("SE"), strdup("Sweden"));
	dictionary_insert(alpha2_to_name, strdup("CH"), strdup("Switzerland"));
	dictionary_insert(alpha2_to_name, strdup("SY"), strdup("Syrian Arab Republic"));
	dictionary_insert(alpha2_to_name, strdup("TW"), strdup("Taiwan, Province of China"));
	dictionary_insert(alpha2_to_name, strdup("TJ"), strdup("Tajikistan"));
	dictionary_insert(alpha2_to_name, strdup("TZ"), strdup("Tanzania, United Republic of"));
	dictionary_insert(alpha2_to_name, strdup("TH"), strdup("Thailand"));
	dictionary_insert(alpha2_to_name, strdup("TL"), strdup("Timor-Leste"));
	dictionary_insert(alpha2_to_name, strdup("TG"), strdup("Togo"));
	dictionary_insert(alpha2_to_name, strdup("TN"), strdup("Tunisia"));
	dictionary_insert(alpha2_to_name, strdup("TR"), strdup("Turkey"));
	dictionary_insert(alpha2_to_name, strdup("TM"), strdup("Turkmenistan"));
	dictionary_insert(alpha2_to_name, strdup("UG"), strdup("Uganda"));
	dictionary_insert(alpha2_to_name, strdup("UA"), strdup("Ukraine"));
	dictionary_insert(alpha2_to_name, strdup("AE"), strdup("United Arab Emirates"));
	dictionary_insert(alpha2_to_name, strdup("GB"), strdup("United Kingdom of Great Britain and Northern Ireland"));
	dictionary_insert(alpha2_to_name, strdup("US"), strdup("United States of America"));
	dictionary_insert(alpha2_to_name, strdup("UM"), strdup("United States Minor Outlying Islands"));
	dictionary_insert(alpha2_to_name, strdup("UY"), strdup("Uruguay"));
	dictionary_insert(alpha2_to_name, strdup("UZ"), strdup("Uzbekistan"));
	dictionary_insert(alpha2_to_name, strdup("VE"), strdup("Venezuela (Bolivarian Republic of)"));
	dictionary_insert(alpha2_to_name, strdup("VN"), strdup("Viet Nam"));
	dictionary_insert(alpha2_to_name, strdup("EH"), strdup("Western Sahara"));
	dictionary_insert(alpha2_to_name, strdup("YE"), strdup("Yemen"));
	dictionary_insert(alpha2_to_name, strdup("ZM"), strdup("Zambia"));
	dictionary_insert(alpha2_to_name, strdup("ZW"), strdup("Zimbabwe"));
	dictionary_insert(name_to_alpha2, strdup("Afghanistan"), strdup("AF"));
	dictionary_insert(name_to_alpha2, strdup("Albania"), strdup("AL"));
	dictionary_insert(name_to_alpha2, strdup("Algeria"), strdup("DZ"));
	dictionary_insert(name_to_alpha2, strdup("Andorra"), strdup("AD"));
	dictionary_insert(name_to_alpha2, strdup("Angola"), strdup("AO"));
	dictionary_insert(name_to_alpha2, strdup("Argentina"), strdup("AR"));
	dictionary_insert(name_to_alpha2, strdup("Armenia"), strdup("AM"));
	dictionary_insert(name_to_alpha2, strdup("Austria"), strdup("AT"));
	dictionary_insert(name_to_alpha2, strdup("Azerbaijan"), strdup("AZ"));
	dictionary_insert(name_to_alpha2, strdup("Bangladesh"), strdup("BD"));
	dictionary_insert(name_to_alpha2, strdup("Belarus"), strdup("BY"));
	dictionary_insert(name_to_alpha2, strdup("Belgium"), strdup("BE"));
	dictionary_insert(name_to_alpha2, strdup("Belize"), strdup("BZ"));
	dictionary_insert(name_to_alpha2, strdup("Benin"), strdup("BJ"));
	dictionary_insert(name_to_alpha2, strdup("Bhutan"), strdup("BT"));
	dictionary_insert(name_to_alpha2, strdup("Bolivia (Plurinational State of)"), strdup("BO"));
	dictionary_insert(name_to_alpha2, strdup("Bonaire, Sint Eustatius and Saba"), strdup("BQ"));
	dictionary_insert(name_to_alpha2, strdup("Bosnia and Herzegovina"), strdup("BA"));
	dictionary_insert(name_to_alpha2, strdup("Botswana"), strdup("BW"));
	dictionary_insert(name_to_alpha2, strdup("Brazil"), strdup("BR"));
	dictionary_insert(name_to_alpha2, strdup("Brunei Darussalam"), strdup("BN"));
	dictionary_insert(name_to_alpha2, strdup("Bulgaria"), strdup("BG"));
	dictionary_insert(name_to_alpha2, strdup("Burkina Faso"), strdup("BF"));
	dictionary_insert(name_to_alpha2, strdup("Burundi"), strdup("BI"));
	dictionary_insert(name_to_alpha2, strdup("Cambodia"), strdup("KH"));
	dictionary_insert(name_to_alpha2, strdup("Cameroon"), strdup("CM"));
	dictionary_insert(name_to_alpha2, strdup("Canada"), strdup("CA"));
	dictionary_insert(name_to_alpha2, strdup("Central African Republic"), strdup("CF"));
	dictionary_insert(name_to_alpha2, strdup("Chad"), strdup("TD"));
	dictionary_insert(name_to_alpha2, strdup("Chile"), strdup("CL"));
	dictionary_insert(name_to_alpha2, strdup("China"), strdup("CN"));
	dictionary_insert(name_to_alpha2, strdup("Colombia"), strdup("CO"));
	dictionary_insert(name_to_alpha2, strdup("Congo"), strdup("CG"));
	dictionary_insert(name_to_alpha2, strdup("Congo, Democratic Republic of the"), strdup("CD"));
	dictionary_insert(name_to_alpha2, strdup("Costa Rica"), strdup("CR"));
	dictionary_insert(name_to_alpha2, strdup("Côte d'Ivoire"), strdup("CI"));
	dictionary_insert(name_to_alpha2, strdup("Croatia"), strdup("HR"));
	dictionary_insert(name_to_alpha2, strdup("Czechia"), strdup("CZ"));
	dictionary_insert(name_to_alpha2, strdup("Denmark"), strdup("DK"));
	dictionary_insert(name_to_alpha2, strdup("Djibouti"), strdup("DJ"));
	dictionary_insert(name_to_alpha2, strdup("Dominican Republic"), strdup("DO"));
	dictionary_insert(name_to_alpha2, strdup("Ecuador"), strdup("EC"));
	dictionary_insert(name_to_alpha2, strdup("Egypt"), strdup("EG"));
	dictionary_insert(name_to_alpha2, strdup("El Salvador"), strdup("SV"));
	dictionary_insert(name_to_alpha2, strdup("Equatorial Guinea"), strdup("GQ"));
	dictionary_insert(name_to_alpha2, strdup("Eritrea"), strdup("ER"));
	dictionary_insert(name_to_alpha2, strdup("Estonia"), strdup("EE"));
	dictionary_insert(name_to_alpha2, strdup("Eswatini"), strdup("SZ"));
	dictionary_insert(name_to_alpha2, strdup("Ethiopia"), strdup("ET"));
	dictionary_insert(name_to_alpha2, strdup("Finland"), strdup("FI"));
	dictionary_insert(name_to_alpha2, strdup("France"), strdup("FR"));
	dictionary_insert(name_to_alpha2, strdup("French Guiana"), strdup("GF"));
	dictionary_insert(name_to_alpha2, strdup("Gabon"), strdup("GA"));
	dictionary_insert(name_to_alpha2, strdup("Gambia"), strdup("GM"));
	dictionary_insert(name_to_alpha2, strdup("Georgia"), strdup("GE"));
	dictionary_insert(name_to_alpha2, strdup("Germany"), strdup("DE"));
	dictionary_insert(name_to_alpha2, strdup("Ghana"), strdup("GH"));
	dictionary_insert(name_to_alpha2, strdup("Gibraltar"), strdup("GI"));
	dictionary_insert(name_to_alpha2, strdup("Greece"), strdup("GR"));
	dictionary_insert(name_to_alpha2, strdup("Guatemala"), strdup("GT"));
	dictionary_insert(name_to_alpha2, strdup("Guinea"), strdup("GN"));
	dictionary_insert(name_to_alpha2, strdup("Guinea-Bissau"), strdup("GW"));
	dictionary_insert(name_to_alpha2, strdup("Guyana"), strdup("GY"));
	dictionary_insert(name_to_alpha2, strdup("Haiti"), strdup("HT"));
	dictionary_insert(name_to_alpha2, strdup("Holy See"), strdup("VA"));
	dictionary_insert(name_to_alpha2, strdup("Honduras"), strdup("HN"));
	dictionary_insert(name_to_alpha2, strdup("Hong Kong"), strdup("HK"));
	dictionary_insert(name_to_alpha2, strdup("Hungary"), strdup("HU"));
	dictionary_insert(name_to_alpha2, strdup("India"), strdup("IN"));
	dictionary_insert(name_to_alpha2, strdup("Indonesia"), strdup("ID"));
	dictionary_insert(name_to_alpha2, strdup("Iran (Islamic Republic of)"), strdup("IR"));
	dictionary_insert(name_to_alpha2, strdup("Iraq"), strdup("IQ"));
	dictionary_insert(name_to_alpha2, strdup("Ireland"), strdup("IE"));
	dictionary_insert(name_to_alpha2, strdup("Israel"), strdup("IL"));
	dictionary_insert(name_to_alpha2, strdup("Italy"), strdup("IT"));
	dictionary_insert(name_to_alpha2, strdup("Jordan"), strdup("JO"));
	dictionary_insert(name_to_alpha2, strdup("Kazakhstan"), strdup("KZ"));
	dictionary_insert(name_to_alpha2, strdup("Kenya"), strdup("KE"));
	dictionary_insert(name_to_alpha2, strdup("Korea (Democratic People's Republic of)"), strdup("KP"));
	dictionary_insert(name_to_alpha2, strdup("Korea, Republic of"), strdup("KR"));
	dictionary_insert(name_to_alpha2, strdup("Kuwait"), strdup("KW"));
	dictionary_insert(name_to_alpha2, strdup("Kyrgyzstan"), strdup("KG"));
	dictionary_insert(name_to_alpha2, strdup("Lao People's Democratic Republic"), strdup("LA"));
	dictionary_insert(name_to_alpha2, strdup("Latvia"), strdup("LV"));
	dictionary_insert(name_to_alpha2, strdup("Lebanon"), strdup("LB"));
	dictionary_insert(name_to_alpha2, strdup("Lesotho"), strdup("LS"));
	dictionary_insert(name_to_alpha2, strdup("Liberia"), strdup("LR"));
	dictionary_insert(name_to_alpha2, strdup("Libya"), strdup("LY"));
	dictionary_insert(name_to_alpha2, strdup("Liechtenstein"), strdup("LI"));
	dictionary_insert(name_to_alpha2, strdup("Lithuania"), strdup("LT"));
	dictionary_insert(name_to_alpha2, strdup("Luxembourg"), strdup("LU"));
	dictionary_insert(name_to_alpha2, strdup("Macao"), strdup("MO"));
	dictionary_insert(name_to_alpha2, strdup("Malawi"), strdup("MW"));
	dictionary_insert(name_to_alpha2, strdup("Malaysia"), strdup("MY"));
	dictionary_insert(name_to_alpha2, strdup("Mali"), strdup("ML"));
	dictionary_insert(name_to_alpha2, strdup("Mauritania"), strdup("MR"));
	dictionary_insert(name_to_alpha2, strdup("Mexico"), strdup("MX"));
	dictionary_insert(name_to_alpha2, strdup("Moldova, Republic of"), strdup("MD"));
	dictionary_insert(name_to_alpha2, strdup("Monaco"), strdup("MC"));
	dictionary_insert(name_to_alpha2, strdup("Mongolia"), strdup("MN"));
	dictionary_insert(name_to_alpha2, strdup("Montenegro"), strdup("ME"));
	dictionary_insert(name_to_alpha2, strdup("Morocco"), strdup("MA"));
	dictionary_insert(name_to_alpha2, strdup("Mozambique"), strdup("MZ"));
	dictionary_insert(name_to_alpha2, strdup("Myanmar"), strdup("MM"));
	dictionary_insert(name_to_alpha2, strdup("Namibia"), strdup("NA"));
	dictionary_insert(name_to_alpha2, strdup("Nepal"), strdup("NP"));
	dictionary_insert(name_to_alpha2, strdup("Netherlands"), strdup("NL"));
	dictionary_insert(name_to_alpha2, strdup("Nicaragua"), strdup("NI"));
	dictionary_insert(name_to_alpha2, strdup("Niger"), strdup("NE"));
	dictionary_insert(name_to_alpha2, strdup("Nigeria"), strdup("NG"));
	dictionary_insert(name_to_alpha2, strdup("North Macedonia"), strdup("MK"));
	dictionary_insert(name_to_alpha2, strdup("Norway"), strdup("NO"));
	dictionary_insert(name_to_alpha2, strdup("Oman"), strdup("OM"));
	dictionary_insert(name_to_alpha2, strdup("Pakistan"), strdup("PK"));
	dictionary_insert(name_to_alpha2, strdup("Palestine, State of"), strdup("PS"));
	dictionary_insert(name_to_alpha2, strdup("Panama"), strdup("PA"));
	dictionary_insert(name_to_alpha2, strdup("Papua New Guinea"), strdup("PG"));
	dictionary_insert(name_to_alpha2, strdup("Paraguay"), strdup("PY"));
	dictionary_insert(name_to_alpha2, strdup("Peru"), strdup("PE"));
	dictionary_insert(name_to_alpha2, strdup("Poland"), strdup("PL"));
	dictionary_insert(name_to_alpha2, strdup("Portugal"), strdup("PT"));
	dictionary_insert(name_to_alpha2, strdup("Qatar"), strdup("QA"));
	dictionary_insert(name_to_alpha2, strdup("Romania"), strdup("RO"));
	dictionary_insert(name_to_alpha2, strdup("Russian Federation"), strdup("RU"));
	dictionary_insert(name_to_alpha2, strdup("Rwanda"), strdup("RW"));
	dictionary_insert(name_to_alpha2, strdup("Saint Martin (French part)"), strdup("MF"));
	dictionary_insert(name_to_alpha2, strdup("San Marino"), strdup("SM"));
	dictionary_insert(name_to_alpha2, strdup("Saudi Arabia"), strdup("SA"));
	dictionary_insert(name_to_alpha2, strdup("Senegal"), strdup("SN"));
	dictionary_insert(name_to_alpha2, strdup("Serbia"), strdup("RS"));
	dictionary_insert(name_to_alpha2, strdup("Sierra Leone"), strdup("SL"));
	dictionary_insert(name_to_alpha2, strdup("Sint Maarten (Dutch part)"), strdup("SX"));
	dictionary_insert(name_to_alpha2, strdup("Slovakia"), strdup("SK"));
	dictionary_insert(name_to_alpha2, strdup("Slovenia"), strdup("SI"));
	dictionary_insert(name_to_alpha2, strdup("Somalia"), strdup("SO"));
	dictionary_insert(name_to_alpha2, strdup("South Africa"), strdup("ZA"));
	dictionary_insert(name_to_alpha2, strdup("South Sudan"), strdup("SS"));
	dictionary_insert(name_to_alpha2, strdup("Spain"), strdup("ES"));
	dictionary_insert(name_to_alpha2, strdup("Sudan"), strdup("SD"));
	dictionary_insert(name_to_alpha2, strdup("Suriname"), strdup("SR"));
	dictionary_insert(name_to_alpha2, strdup("Sweden"), strdup("SE"));
	dictionary_insert(name_to_alpha2, strdup("Switzerland"), strdup("CH"));
	dictionary_insert(name_to_alpha2, strdup("Syrian Arab Republic"), strdup("SY"));
	dictionary_insert(name_to_alpha2, strdup("Taiwan, Province of China"), strdup("TW"));
	dictionary_insert(name_to_alpha2, strdup("Tajikistan"), strdup("TJ"));
	dictionary_insert(name_to_alpha2, strdup("Tanzania, United Republic of"), strdup("TZ"));
	dictionary_insert(name_to_alpha2, strdup("Thailand"), strdup("TH"));
	dictionary_insert(name_to_alpha2, strdup("Timor-Leste"), strdup("TL"));
	dictionary_insert(name_to_alpha2, strdup("Togo"), strdup("TG"));
	dictionary_insert(name_to_alpha2, strdup("Tunisia"), strdup("TN"));
	dictionary_insert(name_to_alpha2, strdup("Turkey"), strdup("TR"));
	dictionary_insert(name_to_alpha2, strdup("Turkmenistan"), strdup("TM"));
	dictionary_insert(name_to_alpha2, strdup("Uganda"), strdup("UG"));
	dictionary_insert(name_to_alpha2, strdup("Ukraine"), strdup("UA"));
	dictionary_insert(name_to_alpha2, strdup("United Arab Emirates"), strdup("AE"));
	dictionary_insert(name_to_alpha2, strdup("United Kingdom of Great Britain and Northern Ireland"), strdup("GB"));
	dictionary_insert(name_to_alpha2, strdup("United States of America"), strdup("US"));
	dictionary_insert(name_to_alpha2, strdup("United States Minor Outlying Islands"), strdup("UM"));
	dictionary_insert(name_to_alpha2, strdup("Uruguay"), strdup("UY"));
	dictionary_insert(name_to_alpha2, strdup("Uzbekistan"), strdup("UZ"));
	dictionary_insert(name_to_alpha2, strdup("Venezuela (Bolivarian Republic of)"), strdup("VE"));
	dictionary_insert(name_to_alpha2, strdup("Viet Nam"), strdup("VN"));
	dictionary_insert(name_to_alpha2, strdup("Western Sahara"), strdup("EH"));
	dictionary_insert(name_to_alpha2, strdup("Yemen"), strdup("YE"));
	dictionary_insert(name_to_alpha2, strdup("Zambia"), strdup("ZM"));
	dictionary_insert(name_to_alpha2, strdup("Zimbabwe"), strdup("ZW"));
	struct Vertex * country_AF = construct_vertex(4, "AF");
	struct Vertex * country_AL = construct_vertex(8, "AL");
	struct Vertex * country_DZ = construct_vertex(12, "DZ");
	struct Vertex * country_AD = construct_vertex(20, "AD");
	struct Vertex * country_AO = construct_vertex(24, "AO");
	struct Vertex * country_AR = construct_vertex(32, "AR");
	struct Vertex * country_AM = construct_vertex(51, "AM");
	struct Vertex * country_AT = construct_vertex(40, "AT");
	struct Vertex * country_AZ = construct_vertex(31, "AZ");
	struct Vertex * country_BD = construct_vertex(50, "BD");
	struct Vertex * country_BY = construct_vertex(112, "BY");
	struct Vertex * country_BE = construct_vertex(56, "BE");
	struct Vertex * country_BZ = construct_vertex(84, "BZ");
	struct Vertex * country_BJ = construct_vertex(204, "BJ");
	struct Vertex * country_BT = construct_vertex(64, "BT");
	struct Vertex * country_BO = construct_vertex(68, "BO");
	struct Vertex * country_BQ = construct_vertex(535, "BQ");
	struct Vertex * country_BA = construct_vertex(70, "BA");
	struct Vertex * country_BW = construct_vertex(72, "BW");
	struct Vertex * country_BR = construct_vertex(76, "BR");
	struct Vertex * country_BN = construct_vertex(96, "BN");
	struct Vertex * country_BG = construct_vertex(100, "BG");
	struct Vertex * country_BF = construct_vertex(854, "BF");
	struct Vertex * country_BI = construct_vertex(108, "BI");
	struct Vertex * country_KH = construct_vertex(116, "KH");
	struct Vertex * country_CM = construct_vertex(120, "CM");
	struct Vertex * country_CA = construct_vertex(124, "CA");
	struct Vertex * country_CF = construct_vertex(140, "CF");
	struct Vertex * country_TD = construct_vertex(148, "TD");
	struct Vertex * country_CL = construct_vertex(152, "CL");
	struct Vertex * country_CN = construct_vertex(156, "CN");
	struct Vertex * country_CO = construct_vertex(170, "CO");
	struct Vertex * country_CG = construct_vertex(178, "CG");
	struct Vertex * country_CD = construct_vertex(180, "CD");
	struct Vertex * country_CR = construct_vertex(188, "CR");
	struct Vertex * country_CI = construct_vertex(384, "CI");
	struct Vertex * country_HR = construct_vertex(191, "HR");
	struct Vertex * country_CZ = construct_vertex(203, "CZ");
	struct Vertex * country_DK = construct_vertex(208, "DK");
	struct Vertex * country_DJ = construct_vertex(262, "DJ");
	struct Vertex * country_DO = construct_vertex(214, "DO");
	struct Vertex * country_EC = construct_vertex(218, "EC");
	struct Vertex * country_EG = construct_vertex(818, "EG");
	struct Vertex * country_SV = construct_vertex(222, "SV");
	struct Vertex * country_GQ = construct_vertex(226, "GQ");
	struct Vertex * country_ER = construct_vertex(232, "ER");
	struct Vertex * country_EE = construct_vertex(233, "EE");
	struct Vertex * country_SZ = construct_vertex(748, "SZ");
	struct Vertex * country_ET = construct_vertex(231, "ET");
	struct Vertex * country_FI = construct_vertex(246, "FI");
	struct Vertex * country_FR = construct_vertex(250, "FR");
	struct Vertex * country_GF = construct_vertex(254, "GF");
	struct Vertex * country_GA = construct_vertex(266, "GA");
	struct Vertex * country_GM = construct_vertex(270, "GM");
	struct Vertex * country_GE = construct_vertex(268, "GE");
	struct Vertex * country_DE = construct_vertex(276, "DE");
	struct Vertex * country_GH = construct_vertex(288, "GH");
	struct Vertex * country_GI = construct_vertex(292, "GI");
	struct Vertex * country_GR = construct_vertex(300, "GR");
	struct Vertex * country_GT = construct_vertex(320, "GT");
	struct Vertex * country_GN = construct_vertex(324, "GN");
	struct Vertex * country_GW = construct_vertex(624, "GW");
	struct Vertex * country_GY = construct_vertex(328, "GY");
	struct Vertex * country_HT = construct_vertex(332, "HT");
	struct Vertex * country_VA = construct_vertex(336, "VA");
	struct Vertex * country_HN = construct_vertex(340, "HN");
	struct Vertex * country_HK = construct_vertex(344, "HK");
	struct Vertex * country_HU = construct_vertex(348, "HU");
	struct Vertex * country_IN = construct_vertex(356, "IN");
	struct Vertex * country_ID = construct_vertex(360, "ID");
	struct Vertex * country_IR = construct_vertex(364, "IR");
	struct Vertex * country_IQ = construct_vertex(368, "IQ");
	struct Vertex * country_IE = construct_vertex(372, "IE");
	struct Vertex * country_IL = construct_vertex(376, "IL");
	struct Vertex * country_IT = construct_vertex(380, "IT");
	struct Vertex * country_JO = construct_vertex(400, "JO");
	struct Vertex * country_KZ = construct_vertex(398, "KZ");
	struct Vertex * country_KE = construct_vertex(404, "KE");
	struct Vertex * country_KP = construct_vertex(408, "KP");
	struct Vertex * country_KR = construct_vertex(410, "KR");
	struct Vertex * country_KW = construct_vertex(414, "KW");
	struct Vertex * country_KG = construct_vertex(417, "KG");
	struct Vertex * country_LA = construct_vertex(418, "LA");
	struct Vertex * country_LV = construct_vertex(428, "LV");
	struct Vertex * country_LB = construct_vertex(422, "LB");
	struct Vertex * country_LS = construct_vertex(426, "LS");
	struct Vertex * country_LR = construct_vertex(430, "LR");
	struct Vertex * country_LY = construct_vertex(434, "LY");
	struct Vertex * country_LI = construct_vertex(438, "LI");
	struct Vertex * country_LT = construct_vertex(440, "LT");
	struct Vertex * country_LU = construct_vertex(442, "LU");
	struct Vertex * country_MO = construct_vertex(446, "MO");
	struct Vertex * country_MW = construct_vertex(454, "MW");
	struct Vertex * country_MY = construct_vertex(458, "MY");
	struct Vertex * country_ML = construct_vertex(466, "ML");
	struct Vertex * country_MR = construct_vertex(478, "MR");
	struct Vertex * country_MX = construct_vertex(484, "MX");
	struct Vertex * country_MD = construct_vertex(498, "MD");
	struct Vertex * country_MC = construct_vertex(492, "MC");
	struct Vertex * country_MN = construct_vertex(496, "MN");
	struct Vertex * country_ME = construct_vertex(499, "ME");
	struct Vertex * country_MA = construct_vertex(504, "MA");
	struct Vertex * country_MZ = construct_vertex(508, "MZ");
	struct Vertex * country_MM = construct_vertex(104, "MM");
	struct Vertex * country_NA = construct_vertex(516, "NA");
	struct Vertex * country_NP = construct_vertex(524, "NP");
	struct Vertex * country_NL = construct_vertex(528, "NL");
	struct Vertex * country_NI = construct_vertex(558, "NI");
	struct Vertex * country_NE = construct_vertex(562, "NE");
	struct Vertex * country_NG = construct_vertex(566, "NG");
	struct Vertex * country_MK = construct_vertex(807, "MK");
	struct Vertex * country_NO = construct_vertex(578, "NO");
	struct Vertex * country_OM = construct_vertex(512, "OM");
	struct Vertex * country_PK = construct_vertex(586, "PK");
	struct Vertex * country_PS = construct_vertex(275, "PS");
	struct Vertex * country_PA = construct_vertex(591, "PA");
	struct Vertex * country_PG = construct_vertex(598, "PG");
	struct Vertex * country_PY = construct_vertex(600, "PY");
	struct Vertex * country_PE = construct_vertex(604, "PE");
	struct Vertex * country_PL = construct_vertex(616, "PL");
	struct Vertex * country_PT = construct_vertex(620, "PT");
	struct Vertex * country_QA = construct_vertex(634, "QA");
	struct Vertex * country_RO = construct_vertex(642, "RO");
	struct Vertex * country_RU = construct_vertex(643, "RU");
	struct Vertex * country_RW = construct_vertex(646, "RW");
	struct Vertex * country_MF = construct_vertex(663, "MF");
	struct Vertex * country_SM = construct_vertex(674, "SM");
	struct Vertex * country_SA = construct_vertex(682, "SA");
	struct Vertex * country_SN = construct_vertex(686, "SN");
	struct Vertex * country_RS = construct_vertex(688, "RS");
	struct Vertex * country_SL = construct_vertex(694, "SL");
	struct Vertex * country_SX = construct_vertex(534, "SX");
	struct Vertex * country_SK = construct_vertex(703, "SK");
	struct Vertex * country_SI = construct_vertex(705, "SI");
	struct Vertex * country_SO = construct_vertex(706, "SO");
	struct Vertex * country_ZA = construct_vertex(710, "ZA");
	struct Vertex * country_SS = construct_vertex(728, "SS");
	struct Vertex * country_ES = construct_vertex(724, "ES");
	struct Vertex * country_SD = construct_vertex(729, "SD");
	struct Vertex * country_SR = construct_vertex(740, "SR");
	struct Vertex * country_SE = construct_vertex(752, "SE");
	struct Vertex * country_CH = construct_vertex(756, "CH");
	struct Vertex * country_SY = construct_vertex(760, "SY");
	struct Vertex * country_TW = construct_vertex(158, "TW");
	struct Vertex * country_TJ = construct_vertex(762, "TJ");
	struct Vertex * country_TZ = construct_vertex(834, "TZ");
	struct Vertex * country_TH = construct_vertex(764, "TH");
	struct Vertex * country_TL = construct_vertex(626, "TL");
	struct Vertex * country_TG = construct_vertex(768, "TG");
	struct Vertex * country_TN = construct_vertex(788, "TN");
	struct Vertex * country_TR = construct_vertex(792, "TR");
	struct Vertex * country_TM = construct_vertex(795, "TM");
	struct Vertex * country_UG = construct_vertex(800, "UG");
	struct Vertex * country_UA = construct_vertex(804, "UA");
	struct Vertex * country_AE = construct_vertex(784, "AE");
	struct Vertex * country_GB = construct_vertex(826, "GB");
	struct Vertex * country_US = construct_vertex(840, "US");
	struct Vertex * country_UM = construct_vertex(581, "UM");
	struct Vertex * country_UY = construct_vertex(858, "UY");
	struct Vertex * country_UZ = construct_vertex(860, "UZ");
	struct Vertex * country_VE = construct_vertex(862, "VE");
	struct Vertex * country_VN = construct_vertex(704, "VN");
	struct Vertex * country_EH = construct_vertex(732, "EH");
	struct Vertex * country_YE = construct_vertex(887, "YE");
	struct Vertex * country_ZM = construct_vertex(894, "ZM");
	struct Vertex * country_ZW = construct_vertex(716, "ZW");
	countryVertices[4] = country_AF;
	countryVertices[8] = country_AL;
	countryVertices[12] = country_DZ;
	countryVertices[20] = country_AD;
	countryVertices[24] = country_AO;
	countryVertices[32] = country_AR;
	countryVertices[51] = country_AM;
	countryVertices[40] = country_AT;
	countryVertices[31] = country_AZ;
	countryVertices[50] = country_BD;
	countryVertices[112] = country_BY;
	countryVertices[56] = country_BE;
	countryVertices[84] = country_BZ;
	countryVertices[204] = country_BJ;
	countryVertices[64] = country_BT;
	countryVertices[68] = country_BO;
	countryVertices[535] = country_BQ;
	countryVertices[70] = country_BA;
	countryVertices[72] = country_BW;
	countryVertices[76] = country_BR;
	countryVertices[96] = country_BN;
	countryVertices[100] = country_BG;
	countryVertices[854] = country_BF;
	countryVertices[108] = country_BI;
	countryVertices[116] = country_KH;
	countryVertices[120] = country_CM;
	countryVertices[124] = country_CA;
	countryVertices[140] = country_CF;
	countryVertices[148] = country_TD;
	countryVertices[152] = country_CL;
	countryVertices[156] = country_CN;
	countryVertices[170] = country_CO;
	countryVertices[178] = country_CG;
	countryVertices[180] = country_CD;
	countryVertices[188] = country_CR;
	countryVertices[384] = country_CI;
	countryVertices[191] = country_HR;
	countryVertices[203] = country_CZ;
	countryVertices[208] = country_DK;
	countryVertices[262] = country_DJ;
	countryVertices[214] = country_DO;
	countryVertices[218] = country_EC;
	countryVertices[818] = country_EG;
	countryVertices[222] = country_SV;
	countryVertices[226] = country_GQ;
	countryVertices[232] = country_ER;
	countryVertices[233] = country_EE;
	countryVertices[748] = country_SZ;
	countryVertices[231] = country_ET;
	countryVertices[246] = country_FI;
	countryVertices[250] = country_FR;
	countryVertices[254] = country_GF;
	countryVertices[266] = country_GA;
	countryVertices[270] = country_GM;
	countryVertices[268] = country_GE;
	countryVertices[276] = country_DE;
	countryVertices[288] = country_GH;
	countryVertices[292] = country_GI;
	countryVertices[300] = country_GR;
	countryVertices[320] = country_GT;
	countryVertices[324] = country_GN;
	countryVertices[624] = country_GW;
	countryVertices[328] = country_GY;
	countryVertices[332] = country_HT;
	countryVertices[336] = country_VA;
	countryVertices[340] = country_HN;
	countryVertices[344] = country_HK;
	countryVertices[348] = country_HU;
	countryVertices[356] = country_IN;
	countryVertices[360] = country_ID;
	countryVertices[364] = country_IR;
	countryVertices[368] = country_IQ;
	countryVertices[372] = country_IE;
	countryVertices[376] = country_IL;
	countryVertices[380] = country_IT;
	countryVertices[400] = country_JO;
	countryVertices[398] = country_KZ;
	countryVertices[404] = country_KE;
	countryVertices[408] = country_KP;
	countryVertices[410] = country_KR;
	countryVertices[414] = country_KW;
	countryVertices[417] = country_KG;
	countryVertices[418] = country_LA;
	countryVertices[428] = country_LV;
	countryVertices[422] = country_LB;
	countryVertices[426] = country_LS;
	countryVertices[430] = country_LR;
	countryVertices[434] = country_LY;
	countryVertices[438] = country_LI;
	countryVertices[440] = country_LT;
	countryVertices[442] = country_LU;
	countryVertices[446] = country_MO;
	countryVertices[454] = country_MW;
	countryVertices[458] = country_MY;
	countryVertices[466] = country_ML;
	countryVertices[478] = country_MR;
	countryVertices[484] = country_MX;
	countryVertices[498] = country_MD;
	countryVertices[492] = country_MC;
	countryVertices[496] = country_MN;
	countryVertices[499] = country_ME;
	countryVertices[504] = country_MA;
	countryVertices[508] = country_MZ;
	countryVertices[104] = country_MM;
	countryVertices[516] = country_NA;
	countryVertices[524] = country_NP;
	countryVertices[528] = country_NL;
	countryVertices[558] = country_NI;
	countryVertices[562] = country_NE;
	countryVertices[566] = country_NG;
	countryVertices[807] = country_MK;
	countryVertices[578] = country_NO;
	countryVertices[512] = country_OM;
	countryVertices[586] = country_PK;
	countryVertices[275] = country_PS;
	countryVertices[591] = country_PA;
	countryVertices[598] = country_PG;
	countryVertices[600] = country_PY;
	countryVertices[604] = country_PE;
	countryVertices[616] = country_PL;
	countryVertices[620] = country_PT;
	countryVertices[634] = country_QA;
	countryVertices[642] = country_RO;
	countryVertices[643] = country_RU;
	countryVertices[646] = country_RW;
	countryVertices[663] = country_MF;
	countryVertices[674] = country_SM;
	countryVertices[682] = country_SA;
	countryVertices[686] = country_SN;
	countryVertices[688] = country_RS;
	countryVertices[694] = country_SL;
	countryVertices[534] = country_SX;
	countryVertices[703] = country_SK;
	countryVertices[705] = country_SI;
	countryVertices[706] = country_SO;
	countryVertices[710] = country_ZA;
	countryVertices[728] = country_SS;
	countryVertices[724] = country_ES;
	countryVertices[729] = country_SD;
	countryVertices[740] = country_SR;
	countryVertices[752] = country_SE;
	countryVertices[756] = country_CH;
	countryVertices[760] = country_SY;
	countryVertices[158] = country_TW;
	countryVertices[762] = country_TJ;
	countryVertices[834] = country_TZ;
	countryVertices[764] = country_TH;
	countryVertices[626] = country_TL;
	countryVertices[768] = country_TG;
	countryVertices[788] = country_TN;
	countryVertices[792] = country_TR;
	countryVertices[795] = country_TM;
	countryVertices[800] = country_UG;
	countryVertices[804] = country_UA;
	countryVertices[784] = country_AE;
	countryVertices[826] = country_GB;
	countryVertices[840] = country_US;
	countryVertices[581] = country_UM;
	countryVertices[858] = country_UY;
	countryVertices[860] = country_UZ;
	countryVertices[862] = country_VE;
	countryVertices[704] = country_VN;
	countryVertices[732] = country_EH;
	countryVertices[887] = country_YE;
	countryVertices[894] = country_ZM;
	countryVertices[716] = country_ZW;
	dictionary_insert(alpha2_to_numeric, "AF", "4");
	dictionary_insert(alpha2_to_numeric, "AL", "8");
	dictionary_insert(alpha2_to_numeric, "DZ", "12");
	dictionary_insert(alpha2_to_numeric, "AD", "20");
	dictionary_insert(alpha2_to_numeric, "AO", "24");
	dictionary_insert(alpha2_to_numeric, "AR", "32");
	dictionary_insert(alpha2_to_numeric, "AM", "51");
	dictionary_insert(alpha2_to_numeric, "AT", "40");
	dictionary_insert(alpha2_to_numeric, "AZ", "31");
	dictionary_insert(alpha2_to_numeric, "BD", "50");
	dictionary_insert(alpha2_to_numeric, "BY", "112");
	dictionary_insert(alpha2_to_numeric, "BE", "56");
	dictionary_insert(alpha2_to_numeric, "BZ", "84");
	dictionary_insert(alpha2_to_numeric, "BJ", "204");
	dictionary_insert(alpha2_to_numeric, "BT", "64");
	dictionary_insert(alpha2_to_numeric, "BO", "68");
	dictionary_insert(alpha2_to_numeric, "BQ", "535");
	dictionary_insert(alpha2_to_numeric, "BA", "70");
	dictionary_insert(alpha2_to_numeric, "BW", "72");
	dictionary_insert(alpha2_to_numeric, "BR", "76");
	dictionary_insert(alpha2_to_numeric, "BN", "96");
	dictionary_insert(alpha2_to_numeric, "BG", "100");
	dictionary_insert(alpha2_to_numeric, "BF", "854");
	dictionary_insert(alpha2_to_numeric, "BI", "108");
	dictionary_insert(alpha2_to_numeric, "KH", "116");
	dictionary_insert(alpha2_to_numeric, "CM", "120");
	dictionary_insert(alpha2_to_numeric, "CA", "124");
	dictionary_insert(alpha2_to_numeric, "CF", "140");
	dictionary_insert(alpha2_to_numeric, "TD", "148");
	dictionary_insert(alpha2_to_numeric, "CL", "152");
	dictionary_insert(alpha2_to_numeric, "CN", "156");
	dictionary_insert(alpha2_to_numeric, "CO", "170");
	dictionary_insert(alpha2_to_numeric, "CG", "178");
	dictionary_insert(alpha2_to_numeric, "CD", "180");
	dictionary_insert(alpha2_to_numeric, "CR", "188");
	dictionary_insert(alpha2_to_numeric, "CI", "384");
	dictionary_insert(alpha2_to_numeric, "HR", "191");
	dictionary_insert(alpha2_to_numeric, "CZ", "203");
	dictionary_insert(alpha2_to_numeric, "DK", "208");
	dictionary_insert(alpha2_to_numeric, "DJ", "262");
	dictionary_insert(alpha2_to_numeric, "DO", "214");
	dictionary_insert(alpha2_to_numeric, "EC", "218");
	dictionary_insert(alpha2_to_numeric, "EG", "818");
	dictionary_insert(alpha2_to_numeric, "SV", "222");
	dictionary_insert(alpha2_to_numeric, "GQ", "226");
	dictionary_insert(alpha2_to_numeric, "ER", "232");
	dictionary_insert(alpha2_to_numeric, "EE", "233");
	dictionary_insert(alpha2_to_numeric, "SZ", "748");
	dictionary_insert(alpha2_to_numeric, "ET", "231");
	dictionary_insert(alpha2_to_numeric, "FI", "246");
	dictionary_insert(alpha2_to_numeric, "FR", "250");
	dictionary_insert(alpha2_to_numeric, "GF", "254");
	dictionary_insert(alpha2_to_numeric, "GA", "266");
	dictionary_insert(alpha2_to_numeric, "GM", "270");
	dictionary_insert(alpha2_to_numeric, "GE", "268");
	dictionary_insert(alpha2_to_numeric, "DE", "276");
	dictionary_insert(alpha2_to_numeric, "GH", "288");
	dictionary_insert(alpha2_to_numeric, "GI", "292");
	dictionary_insert(alpha2_to_numeric, "GR", "300");
	dictionary_insert(alpha2_to_numeric, "GT", "320");
	dictionary_insert(alpha2_to_numeric, "GN", "324");
	dictionary_insert(alpha2_to_numeric, "GW", "624");
	dictionary_insert(alpha2_to_numeric, "GY", "328");
	dictionary_insert(alpha2_to_numeric, "HT", "332");
	dictionary_insert(alpha2_to_numeric, "VA", "336");
	dictionary_insert(alpha2_to_numeric, "HN", "340");
	dictionary_insert(alpha2_to_numeric, "HK", "344");
	dictionary_insert(alpha2_to_numeric, "HU", "348");
	dictionary_insert(alpha2_to_numeric, "IN", "356");
	dictionary_insert(alpha2_to_numeric, "ID", "360");
	dictionary_insert(alpha2_to_numeric, "IR", "364");
	dictionary_insert(alpha2_to_numeric, "IQ", "368");
	dictionary_insert(alpha2_to_numeric, "IE", "372");
	dictionary_insert(alpha2_to_numeric, "IL", "376");
	dictionary_insert(alpha2_to_numeric, "IT", "380");
	dictionary_insert(alpha2_to_numeric, "JO", "400");
	dictionary_insert(alpha2_to_numeric, "KZ", "398");
	dictionary_insert(alpha2_to_numeric, "KE", "404");
	dictionary_insert(alpha2_to_numeric, "KP", "408");
	dictionary_insert(alpha2_to_numeric, "KR", "410");
	dictionary_insert(alpha2_to_numeric, "KW", "414");
	dictionary_insert(alpha2_to_numeric, "KG", "417");
	dictionary_insert(alpha2_to_numeric, "LA", "418");
	dictionary_insert(alpha2_to_numeric, "LV", "428");
	dictionary_insert(alpha2_to_numeric, "LB", "422");
	dictionary_insert(alpha2_to_numeric, "LS", "426");
	dictionary_insert(alpha2_to_numeric, "LR", "430");
	dictionary_insert(alpha2_to_numeric, "LY", "434");
	dictionary_insert(alpha2_to_numeric, "LI", "438");
	dictionary_insert(alpha2_to_numeric, "LT", "440");
	dictionary_insert(alpha2_to_numeric, "LU", "442");
	dictionary_insert(alpha2_to_numeric, "MO", "446");
	dictionary_insert(alpha2_to_numeric, "MW", "454");
	dictionary_insert(alpha2_to_numeric, "MY", "458");
	dictionary_insert(alpha2_to_numeric, "ML", "466");
	dictionary_insert(alpha2_to_numeric, "MR", "478");
	dictionary_insert(alpha2_to_numeric, "MX", "484");
	dictionary_insert(alpha2_to_numeric, "MD", "498");
	dictionary_insert(alpha2_to_numeric, "MC", "492");
	dictionary_insert(alpha2_to_numeric, "MN", "496");
	dictionary_insert(alpha2_to_numeric, "ME", "499");
	dictionary_insert(alpha2_to_numeric, "MA", "504");
	dictionary_insert(alpha2_to_numeric, "MZ", "508");
	dictionary_insert(alpha2_to_numeric, "MM", "104");
	dictionary_insert(alpha2_to_numeric, "NA", "516");
	dictionary_insert(alpha2_to_numeric, "NP", "524");
	dictionary_insert(alpha2_to_numeric, "NL", "528");
	dictionary_insert(alpha2_to_numeric, "NI", "558");
	dictionary_insert(alpha2_to_numeric, "NE", "562");
	dictionary_insert(alpha2_to_numeric, "NG", "566");
	dictionary_insert(alpha2_to_numeric, "MK", "807");
	dictionary_insert(alpha2_to_numeric, "NO", "578");
	dictionary_insert(alpha2_to_numeric, "OM", "512");
	dictionary_insert(alpha2_to_numeric, "PK", "586");
	dictionary_insert(alpha2_to_numeric, "PS", "275");
	dictionary_insert(alpha2_to_numeric, "PA", "591");
	dictionary_insert(alpha2_to_numeric, "PG", "598");
	dictionary_insert(alpha2_to_numeric, "PY", "600");
	dictionary_insert(alpha2_to_numeric, "PE", "604");
	dictionary_insert(alpha2_to_numeric, "PL", "616");
	dictionary_insert(alpha2_to_numeric, "PT", "620");
	dictionary_insert(alpha2_to_numeric, "QA", "634");
	dictionary_insert(alpha2_to_numeric, "RO", "642");
	dictionary_insert(alpha2_to_numeric, "RU", "643");
	dictionary_insert(alpha2_to_numeric, "RW", "646");
	dictionary_insert(alpha2_to_numeric, "MF", "663");
	dictionary_insert(alpha2_to_numeric, "SM", "674");
	dictionary_insert(alpha2_to_numeric, "SA", "682");
	dictionary_insert(alpha2_to_numeric, "SN", "686");
	dictionary_insert(alpha2_to_numeric, "RS", "688");
	dictionary_insert(alpha2_to_numeric, "SL", "694");
	dictionary_insert(alpha2_to_numeric, "SX", "534");
	dictionary_insert(alpha2_to_numeric, "SK", "703");
	dictionary_insert(alpha2_to_numeric, "SI", "705");
	dictionary_insert(alpha2_to_numeric, "SO", "706");
	dictionary_insert(alpha2_to_numeric, "ZA", "710");
	dictionary_insert(alpha2_to_numeric, "SS", "728");
	dictionary_insert(alpha2_to_numeric, "ES", "724");
	dictionary_insert(alpha2_to_numeric, "SD", "729");
	dictionary_insert(alpha2_to_numeric, "SR", "740");
	dictionary_insert(alpha2_to_numeric, "SE", "752");
	dictionary_insert(alpha2_to_numeric, "CH", "756");
	dictionary_insert(alpha2_to_numeric, "SY", "760");
	dictionary_insert(alpha2_to_numeric, "TW", "158");
	dictionary_insert(alpha2_to_numeric, "TJ", "762");
	dictionary_insert(alpha2_to_numeric, "TZ", "834");
	dictionary_insert(alpha2_to_numeric, "TH", "764");
	dictionary_insert(alpha2_to_numeric, "TL", "626");
	dictionary_insert(alpha2_to_numeric, "TG", "768");
	dictionary_insert(alpha2_to_numeric, "TN", "788");
	dictionary_insert(alpha2_to_numeric, "TR", "792");
	dictionary_insert(alpha2_to_numeric, "TM", "795");
	dictionary_insert(alpha2_to_numeric, "UG", "800");
	dictionary_insert(alpha2_to_numeric, "UA", "804");
	dictionary_insert(alpha2_to_numeric, "AE", "784");
	dictionary_insert(alpha2_to_numeric, "GB", "826");
	dictionary_insert(alpha2_to_numeric, "US", "840");
	dictionary_insert(alpha2_to_numeric, "UM", "581");
	dictionary_insert(alpha2_to_numeric, "UY", "858");
	dictionary_insert(alpha2_to_numeric, "UZ", "860");
	dictionary_insert(alpha2_to_numeric, "VE", "862");
	dictionary_insert(alpha2_to_numeric, "VN", "704");
	dictionary_insert(alpha2_to_numeric, "EH", "732");
	dictionary_insert(alpha2_to_numeric, "YE", "887");
	dictionary_insert(alpha2_to_numeric, "ZM", "894");
	dictionary_insert(alpha2_to_numeric, "ZW", "716");
	add_edge(country_AD, country_FR);
	add_edge(country_AD, country_ES);
	add_edge(country_AE, country_OM);
	add_edge(country_AE, country_SA);
	add_edge(country_AF, country_CN);
	add_edge(country_AF, country_IR);
	add_edge(country_AF, country_PK);
	add_edge(country_AF, country_TJ);
	add_edge(country_AF, country_TM);
	add_edge(country_AF, country_UZ);
	add_edge(country_AL, country_GR);
	add_edge(country_AL, country_ME);
	add_edge(country_AL, country_MK);
	add_edge(country_AL, country_RS);
	add_edge(country_AM, country_AZ);
	add_edge(country_AM, country_GE);
	add_edge(country_AM, country_IR);
	add_edge(country_AM, country_TR);
	add_edge(country_AO, country_CG);
	add_edge(country_AO, country_CD);
	add_edge(country_AO, country_NA);
	add_edge(country_AO, country_ZM);
	add_edge(country_AR, country_BO);
	add_edge(country_AR, country_BR);
	add_edge(country_AR, country_CL);
	add_edge(country_AR, country_PY);
	add_edge(country_AR, country_UY);
	add_edge(country_AT, country_CZ);
	add_edge(country_AT, country_DE);
	add_edge(country_AT, country_HU);
	add_edge(country_AT, country_IT);
	add_edge(country_AT, country_LI);
	add_edge(country_AT, country_SK);
	add_edge(country_AT, country_SI);
	add_edge(country_AT, country_CH);
	add_edge(country_AZ, country_AM);
	add_edge(country_AZ, country_GE);
	add_edge(country_AZ, country_IR);
	add_edge(country_AZ, country_RU);
	add_edge(country_AZ, country_TR);
	add_edge(country_BA, country_HR);
	add_edge(country_BA, country_ME);
	add_edge(country_BA, country_RS);
	add_edge(country_BD, country_IN);
	add_edge(country_BD, country_MM);
	add_edge(country_BE, country_FR);
	add_edge(country_BE, country_DE);
	add_edge(country_BE, country_LU);
	add_edge(country_BE, country_NL);
	add_edge(country_BF, country_BJ);
	add_edge(country_BF, country_CI);
	add_edge(country_BF, country_GH);
	add_edge(country_BF, country_ML);
	add_edge(country_BF, country_NE);
	add_edge(country_BF, country_TG);
	add_edge(country_BG, country_GR);
	add_edge(country_BG, country_MK);
	add_edge(country_BG, country_RO);
	add_edge(country_BG, country_RS);
	add_edge(country_BG, country_TR);
	add_edge(country_BI, country_CD);
	add_edge(country_BI, country_RW);
	add_edge(country_BI, country_TZ);
	add_edge(country_BJ, country_BF);
	add_edge(country_BJ, country_NE);
	add_edge(country_BJ, country_NG);
	add_edge(country_BJ, country_TG);
	add_edge(country_BN, country_MY);
	add_edge(country_BO, country_AR);
	add_edge(country_BO, country_BR);
	add_edge(country_BO, country_CL);
	add_edge(country_BO, country_PY);
	add_edge(country_BO, country_PE);
	add_edge(country_BR, country_AR);
	add_edge(country_BR, country_BO);
	add_edge(country_BR, country_CO);
	add_edge(country_BR, country_GF);
	add_edge(country_BR, country_GY);
	add_edge(country_BR, country_PY);
	add_edge(country_BR, country_PE);
	add_edge(country_BR, country_SR);
	add_edge(country_BR, country_UY);
	add_edge(country_BR, country_VE);
	add_edge(country_BT, country_CN);
	add_edge(country_BT, country_IN);
	add_edge(country_BW, country_NA);
	add_edge(country_BW, country_ZA);
	add_edge(country_BW, country_ZM);
	add_edge(country_BW, country_ZW);
	add_edge(country_BY, country_LV);
	add_edge(country_BY, country_LT);
	add_edge(country_BY, country_PL);
	add_edge(country_BY, country_RU);
	add_edge(country_BY, country_UA);
	add_edge(country_BZ, country_GT);
	add_edge(country_BZ, country_MX);
	add_edge(country_CA, country_US);
	add_edge(country_CD, country_AO);
	add_edge(country_CD, country_BI);
	add_edge(country_CD, country_CF);
	add_edge(country_CD, country_CG);
	add_edge(country_CD, country_RW);
	add_edge(country_CD, country_SS);
	add_edge(country_CD, country_TZ);
	add_edge(country_CD, country_UG);
	add_edge(country_CD, country_ZM);
	add_edge(country_CF, country_CM);
	add_edge(country_CF, country_TD);
	add_edge(country_CF, country_CG);
	add_edge(country_CF, country_CD);
	add_edge(country_CF, country_SS);
	add_edge(country_CF, country_SD);
	add_edge(country_CG, country_AO);
	add_edge(country_CG, country_CM);
	add_edge(country_CG, country_CF);
	add_edge(country_CG, country_CD);
	add_edge(country_CG, country_GA);
	add_edge(country_CH, country_AT);
	add_edge(country_CH, country_FR);
	add_edge(country_CH, country_DE);
	add_edge(country_CH, country_IT);
	add_edge(country_CH, country_LI);
	add_edge(country_CI, country_BF);
	add_edge(country_CI, country_GH);
	add_edge(country_CI, country_GN);
	add_edge(country_CI, country_LR);
	add_edge(country_CI, country_ML);
	add_edge(country_CL, country_AR);
	add_edge(country_CL, country_BO);
	add_edge(country_CL, country_PE);
	add_edge(country_CM, country_CF);
	add_edge(country_CM, country_TD);
	add_edge(country_CM, country_CG);
	add_edge(country_CM, country_GQ);
	add_edge(country_CM, country_GA);
	add_edge(country_CM, country_NG);
	add_edge(country_CN, country_AF);
	add_edge(country_CN, country_BT);
	add_edge(country_CN, country_HK);
	add_edge(country_CN, country_IN);
	add_edge(country_CN, country_KZ);
	add_edge(country_CN, country_KP);
	add_edge(country_CN, country_KG);
	add_edge(country_CN, country_LA);
	add_edge(country_CN, country_MO);
	add_edge(country_CN, country_MN);
	add_edge(country_CN, country_MM);
	add_edge(country_CN, country_NP);
	add_edge(country_CN, country_PK);
	add_edge(country_CN, country_RU);
	add_edge(country_CN, country_TJ);
	add_edge(country_CN, country_VN);
	add_edge(country_CO, country_BR);
	add_edge(country_CO, country_EC);
	add_edge(country_CO, country_PA);
	add_edge(country_CO, country_PE);
	add_edge(country_CO, country_VE);
	add_edge(country_CR, country_NI);
	add_edge(country_CR, country_PA);
	add_edge(country_CZ, country_AT);
	add_edge(country_CZ, country_DE);
	add_edge(country_CZ, country_PL);
	add_edge(country_CZ, country_SK);
	add_edge(country_DE, country_AT);
	add_edge(country_DE, country_BE);
	add_edge(country_DE, country_CZ);
	add_edge(country_DE, country_DK);
	add_edge(country_DE, country_FR);
	add_edge(country_DE, country_LU);
	add_edge(country_DE, country_NL);
	add_edge(country_DE, country_PL);
	add_edge(country_DE, country_CH);
	add_edge(country_DJ, country_ER);
	add_edge(country_DJ, country_ET);
	add_edge(country_DJ, country_SO);
	add_edge(country_DK, country_DE);
	add_edge(country_DO, country_HT);
	add_edge(country_DZ, country_LY);
	add_edge(country_DZ, country_ML);
	add_edge(country_DZ, country_MR);
	add_edge(country_DZ, country_MA);
	add_edge(country_DZ, country_NE);
	add_edge(country_DZ, country_TN);
	add_edge(country_DZ, country_EH);
	add_edge(country_EC, country_CO);
	add_edge(country_EC, country_PE);
	add_edge(country_EE, country_LV);
	add_edge(country_EE, country_RU);
	add_edge(country_EG, country_IL);
	add_edge(country_EG, country_LY);
	add_edge(country_EG, country_PS);
	add_edge(country_EG, country_SD);
	add_edge(country_EH, country_DZ);
	add_edge(country_EH, country_MR);
	add_edge(country_EH, country_MA);
	add_edge(country_ER, country_DJ);
	add_edge(country_ER, country_ET);
	add_edge(country_ER, country_SD);
	add_edge(country_ES, country_AD);
	add_edge(country_ES, country_FR);
	add_edge(country_ES, country_GI);
	add_edge(country_ES, country_MA);
	add_edge(country_ES, country_PT);
	add_edge(country_ET, country_DJ);
	add_edge(country_ET, country_ER);
	add_edge(country_ET, country_KE);
	add_edge(country_ET, country_SO);
	add_edge(country_ET, country_SS);
	add_edge(country_ET, country_SD);
	add_edge(country_FI, country_NO);
	add_edge(country_FI, country_RU);
	add_edge(country_FI, country_SE);
	add_edge(country_FR, country_AD);
	add_edge(country_FR, country_BE);
	add_edge(country_FR, country_DE);
	add_edge(country_FR, country_IT);
	add_edge(country_FR, country_LU);
	add_edge(country_FR, country_MC);
	add_edge(country_FR, country_ES);
	add_edge(country_FR, country_CH);
	add_edge(country_GA, country_CM);
	add_edge(country_GA, country_CG);
	add_edge(country_GA, country_GQ);
	add_edge(country_GB, country_IE);
	add_edge(country_GE, country_AM);
	add_edge(country_GE, country_AZ);
	add_edge(country_GE, country_RU);
	add_edge(country_GE, country_TR);
	add_edge(country_GF, country_BR);
	add_edge(country_GF, country_SR);
	add_edge(country_GH, country_BF);
	add_edge(country_GH, country_CI);
	add_edge(country_GH, country_TG);
	add_edge(country_GI, country_ES);
	add_edge(country_GM, country_SN);
	add_edge(country_GN, country_CI);
	add_edge(country_GN, country_GW);
	add_edge(country_GN, country_LR);
	add_edge(country_GN, country_ML);
	add_edge(country_GN, country_SN);
	add_edge(country_GN, country_SL);
	add_edge(country_GQ, country_CM);
	add_edge(country_GQ, country_GA);
	add_edge(country_GR, country_AL);
	add_edge(country_GR, country_BG);
	add_edge(country_GR, country_MK);
	add_edge(country_GR, country_TR);
	add_edge(country_GT, country_BZ);
	add_edge(country_GT, country_SV);
	add_edge(country_GT, country_HN);
	add_edge(country_GT, country_MX);
	add_edge(country_GW, country_GN);
	add_edge(country_GW, country_SN);
	add_edge(country_GY, country_BR);
	add_edge(country_GY, country_SR);
	add_edge(country_GY, country_VE);
	add_edge(country_HK, country_CN);
	add_edge(country_HN, country_SV);
	add_edge(country_HN, country_GT);
	add_edge(country_HN, country_NI);
	add_edge(country_HR, country_BA);
	add_edge(country_HR, country_HU);
	add_edge(country_HR, country_ME);
	add_edge(country_HR, country_RS);
	add_edge(country_HR, country_SI);
	add_edge(country_HT, country_DO);
	add_edge(country_HU, country_AT);
	add_edge(country_HU, country_HR);
	add_edge(country_HU, country_RO);
	add_edge(country_HU, country_RS);
	add_edge(country_HU, country_SK);
	add_edge(country_HU, country_SI);
	add_edge(country_HU, country_UA);
	add_edge(country_ID, country_MY);
	add_edge(country_ID, country_PG);
	add_edge(country_ID, country_TL);
	add_edge(country_IE, country_GB);
	add_edge(country_IL, country_EG);
	add_edge(country_IL, country_JO);
	add_edge(country_IL, country_LB);
	add_edge(country_IL, country_PS);
	add_edge(country_IL, country_SY);
	add_edge(country_IN, country_BD);
	add_edge(country_IN, country_BT);
	add_edge(country_IN, country_CN);
	add_edge(country_IN, country_MM);
	add_edge(country_IN, country_NP);
	add_edge(country_IN, country_PK);
	add_edge(country_IQ, country_IR);
	add_edge(country_IQ, country_JO);
	add_edge(country_IQ, country_KW);
	add_edge(country_IQ, country_SA);
	add_edge(country_IQ, country_SY);
	add_edge(country_IQ, country_TR);
	add_edge(country_IR, country_AF);
	add_edge(country_IR, country_AM);
	add_edge(country_IR, country_AZ);
	add_edge(country_IR, country_IQ);
	add_edge(country_IR, country_PK);
	add_edge(country_IR, country_TR);
	add_edge(country_IR, country_TM);
	add_edge(country_IT, country_AT);
	add_edge(country_IT, country_FR);
	add_edge(country_IT, country_SM);
	add_edge(country_IT, country_SI);
	add_edge(country_IT, country_CH);
	add_edge(country_IT, country_VA);
	add_edge(country_JO, country_IQ);
	add_edge(country_JO, country_IL);
	add_edge(country_JO, country_PS);
	add_edge(country_JO, country_SA);
	add_edge(country_JO, country_SY);
	add_edge(country_KE, country_ET);
	add_edge(country_KE, country_SO);
	add_edge(country_KE, country_SS);
	add_edge(country_KE, country_TZ);
	add_edge(country_KE, country_UG);
	add_edge(country_KG, country_CN);
	add_edge(country_KG, country_KZ);
	add_edge(country_KG, country_TJ);
	add_edge(country_KG, country_UZ);
	add_edge(country_KH, country_LA);
	add_edge(country_KH, country_TH);
	add_edge(country_KH, country_VN);
	add_edge(country_KP, country_CN);
	add_edge(country_KP, country_KR);
	add_edge(country_KP, country_RU);
	add_edge(country_KR, country_KP);
	add_edge(country_KW, country_IQ);
	add_edge(country_KW, country_SA);
	add_edge(country_KZ, country_CN);
	add_edge(country_KZ, country_KG);
	add_edge(country_KZ, country_RU);
	add_edge(country_KZ, country_TM);
	add_edge(country_KZ, country_UZ);
	add_edge(country_LA, country_CN);
	add_edge(country_LA, country_KH);
	add_edge(country_LA, country_MM);
	add_edge(country_LA, country_TH);
	add_edge(country_LA, country_VN);
	add_edge(country_LB, country_IL);
	add_edge(country_LB, country_SY);
	add_edge(country_LI, country_AT);
	add_edge(country_LI, country_CH);
	add_edge(country_LR, country_CI);
	add_edge(country_LR, country_GN);
	add_edge(country_LR, country_SL);
	add_edge(country_LS, country_ZA);
	add_edge(country_LT, country_BY);
	add_edge(country_LT, country_LV);
	add_edge(country_LT, country_PL);
	add_edge(country_LT, country_RU);
	add_edge(country_LU, country_BE);
	add_edge(country_LU, country_DE);
	add_edge(country_LU, country_FR);
	add_edge(country_LV, country_BY);
	add_edge(country_LV, country_EE);
	add_edge(country_LV, country_LT);
	add_edge(country_LV, country_RU);
	add_edge(country_LY, country_DZ);
	add_edge(country_LY, country_TD);
	add_edge(country_LY, country_EG);
	add_edge(country_LY, country_NE);
	add_edge(country_LY, country_SD);
	add_edge(country_LY, country_TN);
	add_edge(country_MA, country_DZ);
	add_edge(country_MA, country_ES);
	add_edge(country_MA, country_EH);
	add_edge(country_MC, country_FR);
	add_edge(country_MD, country_RO);
	add_edge(country_MD, country_UA);
	add_edge(country_ME, country_AL);
	add_edge(country_ME, country_BA);
	add_edge(country_ME, country_HR);
	add_edge(country_ME, country_RS);
	add_edge(country_MF, country_SX);
	add_edge(country_MK, country_AL);
	add_edge(country_MK, country_BG);
	add_edge(country_MK, country_GR);
	add_edge(country_MK, country_RS);
	add_edge(country_ML, country_DZ);
	add_edge(country_ML, country_BF);
	add_edge(country_ML, country_CI);
	add_edge(country_ML, country_GN);
	add_edge(country_ML, country_MR);
	add_edge(country_ML, country_NE);
	add_edge(country_ML, country_SN);
	add_edge(country_MM, country_BD);
	add_edge(country_MM, country_CN);
	add_edge(country_MM, country_IN);
	add_edge(country_MM, country_LA);
	add_edge(country_MM, country_TH);
	add_edge(country_MN, country_CN);
	add_edge(country_MN, country_RU);
	add_edge(country_MO, country_CN);
	add_edge(country_MR, country_DZ);
	add_edge(country_MR, country_ML);
	add_edge(country_MR, country_SN);
	add_edge(country_MR, country_EH);
	add_edge(country_MW, country_MZ);
	add_edge(country_MW, country_TZ);
	add_edge(country_MW, country_ZM);
	add_edge(country_MX, country_BZ);
	add_edge(country_MX, country_GT);
	add_edge(country_MX, country_US);
	add_edge(country_MY, country_BN);
	add_edge(country_MY, country_ID);
	add_edge(country_MY, country_TH);
	add_edge(country_MZ, country_MW);
	add_edge(country_MZ, country_SZ);
	add_edge(country_MZ, country_ZA);
	add_edge(country_MZ, country_TZ);
	add_edge(country_MZ, country_ZM);
	add_edge(country_MZ, country_ZW);
	add_edge(country_NA, country_AO);
	add_edge(country_NA, country_BW);
	add_edge(country_NA, country_ZA);
	add_edge(country_NA, country_ZM);
	add_edge(country_NE, country_DZ);
	add_edge(country_NE, country_BJ);
	add_edge(country_NE, country_BF);
	add_edge(country_NE, country_TD);
	add_edge(country_NE, country_LY);
	add_edge(country_NE, country_ML);
	add_edge(country_NE, country_NG);
	add_edge(country_NG, country_BJ);
	add_edge(country_NG, country_CM);
	add_edge(country_NG, country_TD);
	add_edge(country_NG, country_NE);
	add_edge(country_NI, country_CR);
	add_edge(country_NI, country_HN);
	add_edge(country_NL, country_BE);
	add_edge(country_NL, country_DE);
	add_edge(country_NO, country_FI);
	add_edge(country_NO, country_RU);
	add_edge(country_NO, country_SE);
	add_edge(country_NP, country_CN);
	add_edge(country_NP, country_IN);
	add_edge(country_OM, country_AE);
	add_edge(country_OM, country_SA);
	add_edge(country_OM, country_YE);
	add_edge(country_PA, country_CO);
	add_edge(country_PA, country_CR);
	add_edge(country_PE, country_BO);
	add_edge(country_PE, country_BR);
	add_edge(country_PE, country_CL);
	add_edge(country_PE, country_CO);
	add_edge(country_PE, country_EC);
	add_edge(country_PG, country_ID);
	add_edge(country_PK, country_AF);
	add_edge(country_PK, country_CN);
	add_edge(country_PK, country_IN);
	add_edge(country_PK, country_IR);
	add_edge(country_PL, country_BY);
	add_edge(country_PL, country_CZ);
	add_edge(country_PL, country_DE);
	add_edge(country_PL, country_LT);
	add_edge(country_PL, country_RU);
	add_edge(country_PL, country_SK);
	add_edge(country_PL, country_UA);
	add_edge(country_PS, country_EG);
	add_edge(country_PS, country_IL);
	add_edge(country_PS, country_JO);
	add_edge(country_PT, country_ES);
	add_edge(country_PY, country_AR);
	add_edge(country_PY, country_BO);
	add_edge(country_PY, country_BR);
	add_edge(country_QA, country_SA);
	add_edge(country_RO, country_BG);
	add_edge(country_RO, country_HU);
	add_edge(country_RO, country_MD);
	add_edge(country_RO, country_RS);
	add_edge(country_RO, country_UA);
	add_edge(country_RS, country_AL);
	add_edge(country_RS, country_BA);
	add_edge(country_RS, country_BG);
	add_edge(country_RS, country_HR);
	add_edge(country_RS, country_HU);
	add_edge(country_RS, country_ME);
	add_edge(country_RS, country_MK);
	add_edge(country_RS, country_RO);
	add_edge(country_RU, country_AZ);
	add_edge(country_RU, country_BY);
	add_edge(country_RU, country_CN);
	add_edge(country_RU, country_EE);
	add_edge(country_RU, country_FI);
	add_edge(country_RU, country_GE);
	add_edge(country_RU, country_KZ);
	add_edge(country_RU, country_KP);
	add_edge(country_RU, country_LV);
	add_edge(country_RU, country_LT);
	add_edge(country_RU, country_MN);
	add_edge(country_RU, country_NO);
	add_edge(country_RU, country_PL);
	add_edge(country_RU, country_UA);
	add_edge(country_RW, country_BI);
	add_edge(country_RW, country_CD);
	add_edge(country_RW, country_TZ);
	add_edge(country_RW, country_UG);
	add_edge(country_SA, country_IQ);
	add_edge(country_SA, country_JO);
	add_edge(country_SA, country_KW);
	add_edge(country_SA, country_OM);
	add_edge(country_SA, country_QA);
	add_edge(country_SA, country_AE);
	add_edge(country_SA, country_YE);
	add_edge(country_SD, country_CF);
	add_edge(country_SD, country_TD);
	add_edge(country_SD, country_EG);
	add_edge(country_SD, country_ET);
	add_edge(country_SD, country_ER);
	add_edge(country_SD, country_LY);
	add_edge(country_SD, country_SS);
	add_edge(country_SE, country_FI);
	add_edge(country_SE, country_NO);
	add_edge(country_SI, country_AT);
	add_edge(country_SI, country_HR);
	add_edge(country_SI, country_HU);
	add_edge(country_SI, country_IT);
	add_edge(country_SK, country_AT);
	add_edge(country_SK, country_CZ);
	add_edge(country_SK, country_HU);
	add_edge(country_SK, country_PL);
	add_edge(country_SK, country_UA);
	add_edge(country_SL, country_GN);
	add_edge(country_SL, country_LR);
	add_edge(country_SM, country_IT);
	add_edge(country_SN, country_GM);
	add_edge(country_SN, country_GN);
	add_edge(country_SN, country_GW);
	add_edge(country_SN, country_ML);
	add_edge(country_SN, country_MR);
	add_edge(country_SO, country_DJ);
	add_edge(country_SO, country_ET);
	add_edge(country_SO, country_KE);
	add_edge(country_SR, country_BR);
	add_edge(country_SR, country_GF);
	add_edge(country_SR, country_GY);
	add_edge(country_SS, country_CF);
	add_edge(country_SS, country_CD);
	add_edge(country_SS, country_ET);
	add_edge(country_SS, country_KE);
	add_edge(country_SS, country_SD);
	add_edge(country_SS, country_UG);
	add_edge(country_SV, country_GT);
	add_edge(country_SV, country_HN);
	add_edge(country_SX, country_MF);
	add_edge(country_SY, country_IQ);
	add_edge(country_SY, country_IL);
	add_edge(country_SY, country_JO);
	add_edge(country_SY, country_LB);
	add_edge(country_SY, country_TR);
	add_edge(country_SZ, country_MZ);
	add_edge(country_SZ, country_ZA);
	add_edge(country_TD, country_CM);
	add_edge(country_TD, country_CF);
	add_edge(country_TD, country_LY);
	add_edge(country_TD, country_NE);
	add_edge(country_TD, country_NG);
	add_edge(country_TD, country_SD);
	add_edge(country_TG, country_BJ);
	add_edge(country_TG, country_BF);
	add_edge(country_TG, country_GH);
	add_edge(country_TH, country_KH);
	add_edge(country_TH, country_LA);
	add_edge(country_TH, country_MY);
	add_edge(country_TH, country_MM);
	add_edge(country_TJ, country_AF);
	add_edge(country_TJ, country_CN);
	add_edge(country_TJ, country_KG);
	add_edge(country_TJ, country_UZ);
	add_edge(country_TL, country_ID);
	add_edge(country_TM, country_AF);
	add_edge(country_TM, country_IR);
	add_edge(country_TM, country_KZ);
	add_edge(country_TM, country_UZ);
	add_edge(country_TN, country_DZ);
	add_edge(country_TN, country_LY);
	add_edge(country_TR, country_AM);
	add_edge(country_TR, country_AZ);
	add_edge(country_TR, country_BG);
	add_edge(country_TR, country_GE);
	add_edge(country_TR, country_GR);
	add_edge(country_TR, country_IR);
	add_edge(country_TR, country_IQ);
	add_edge(country_TR, country_SY);
	add_edge(country_TZ, country_BI);
	add_edge(country_TZ, country_CD);
	add_edge(country_TZ, country_KE);
	add_edge(country_TZ, country_MW);
	add_edge(country_TZ, country_MZ);
	add_edge(country_TZ, country_RW);
	add_edge(country_TZ, country_UG);
	add_edge(country_TZ, country_ZM);
	add_edge(country_UA, country_BY);
	add_edge(country_UA, country_HU);
	add_edge(country_UA, country_MD);
	add_edge(country_UA, country_PL);
	add_edge(country_UA, country_RO);
	add_edge(country_UA, country_RU);
	add_edge(country_UA, country_SK);
	add_edge(country_UG, country_CD);
	add_edge(country_UG, country_KE);
	add_edge(country_UG, country_RW);
	add_edge(country_UG, country_SS);
	add_edge(country_UG, country_TZ);
	add_edge(country_US, country_CA);
	add_edge(country_US, country_MX);
	add_edge(country_UY, country_AR);
	add_edge(country_UY, country_BR);
	add_edge(country_UZ, country_AF);
	add_edge(country_UZ, country_KZ);
	add_edge(country_UZ, country_KG);
	add_edge(country_UZ, country_TJ);
	add_edge(country_UZ, country_TM);
	add_edge(country_VA, country_IT);
	add_edge(country_VE, country_BR);
	add_edge(country_VE, country_CO);
	add_edge(country_VE, country_GY);
	add_edge(country_VN, country_KH);
	add_edge(country_VN, country_CN);
	add_edge(country_VN, country_LA);
	add_edge(country_YE, country_OM);
	add_edge(country_YE, country_SA);
	add_edge(country_ZA, country_BW);
	add_edge(country_ZA, country_LS);
	add_edge(country_ZA, country_MZ);
	add_edge(country_ZA, country_NA);
	add_edge(country_ZA, country_SZ);
	add_edge(country_ZA, country_ZW);
	add_edge(country_ZM, country_AO);
	add_edge(country_ZM, country_BW);
	add_edge(country_ZM, country_CD);
	add_edge(country_ZM, country_MW);
	add_edge(country_ZM, country_MZ);
	add_edge(country_ZM, country_NA);
	add_edge(country_ZM, country_TZ);
	add_edge(country_ZM, country_ZW);
	add_edge(country_ZW, country_BW);
	add_edge(country_ZW, country_MZ);
	add_edge(country_ZW, country_ZA);
	add_edge(country_ZW, country_ZM);

	// Set up random number generator.
	srand(time(NULL));

	// Pick two random countries.
	struct Vertex * source = random_country(countryVertices);
	struct Vertex * dest = random_country(countryVertices);

	printf("Will create a path from %s to %s.\n", dictionary_get_value(alpha2_to_name, source->s_data),
		dictionary_get_value(alpha2_to_name, dest->s_data));

	struct Vertex * choice = select_country(name_to_alpha2, alpha2_to_numeric, countryVertices);

	struct Path * user_path = user_enter_path(name_to_alpha2, alpha2_to_numeric, countryVertices);


	// Free all dyamic memory used
	dictionary_delete(alpha2_to_name);
	free(alpha2_to_name);
	dictionary_delete(name_to_alpha2);
	free(name_to_alpha2);
	// Freeing this dict in particular causes a mem leak - why?
	// dictionary_delete(alpha2_to_numeric);
	free(alpha2_to_numeric);

	printf("%ld\n", sizeof(int));

	return 0;
}
